import { StorefrontHeader, StorefrontFooter } from "../../storefront/StorefrontChrome";
import "./ditto.css";
import NavigationLink from "./components/navigation-link";
import MegaMenuCategory from "./components/mega-menu-category";
import FilterMenuTrigger from "./components/filter-menu-trigger";
import ProductCard from "./components/product-card";
// Generated by clone-site. Do not edit by hand.
const NavigationLink_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kaffeemaschinen", label: "Kaffeemaschinen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/heissluftfritteusen", label: "Heißluftfritteusen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/mixer", label: "Mixer" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/wasserkocher", label: "Wasserkocher" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/toaster", label: "Toaster" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kuchenmaschinen", label: "Küchenmaschinen" }
];
const MegaMenuCategory_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/air-and-climate", label: "Luft & Klima", href2: "https://demo.spreecommerce.org/de/de/c/air-and-climate/luftreiniger", label2: "Luftreiniger", href3: "https://demo.spreecommerce.org/de/de/c/air-and-climate/luftbefeuchter", label3: "Luftbefeuchter", href4: "https://demo.spreecommerce.org/de/de/c/air-and-climate/ventilator", label4: "Ventilator" },
    { href: "https://demo.spreecommerce.org/de/de/c/garment-care", label: "Kleidungspflege", href2: "https://demo.spreecommerce.org/de/de/c/garment-care/dampferzeuger", label2: "Dampferzeuger", href3: "https://demo.spreecommerce.org/de/de/c/garment-care/handdampfreiniger", label3: "Handdampfreiniger", href4: "https://demo.spreecommerce.org/de/de/c/garment-care/bugeleisen", label4: "Bügeleisen" },
    { href: "https://demo.spreecommerce.org/de/de/c/floor-care", label: "Bodenpflege", href2: "https://demo.spreecommerce.org/de/de/c/floor-care/akku-staubsauger", label2: "Akku-Staubsauger", href3: "https://demo.spreecommerce.org/de/de/c/floor-care/saugroboter", label3: "Saugroboter", href4: "https://demo.spreecommerce.org/de/de/c/floor-care/aufrechte-staubsauger", label4: "Aufrechte Staubsauger" }
];
const NavigationLink_data2 = [
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haartrockner", label: "Haartrockner" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haarglatter", label: "Haarglätter" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haartrimmer", label: "Haartrimmer" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/elektrorasierer", label: "Elektrorasierer" }
];
const FilterMenuTrigger_data = [
    { id: "radix-_R_59clubriujpfivb_", label: "Farbe" },
    { id: "radix-_R_29clubriujpfivb_", label: "Preis" },
    { id: "radix-_R_39clubriujpfivb_", label: "Verfügbarkeit" }
];
const ProductCard_data = [
    { alt: "Digitale Heißluftfritteuse 6.2L", imgSrc: "/assets/cloned/images/4467de6bff7e.jpg", href: "/de/de/products/digitale-heissluftfritteuse-6-2l", title: "Digitale Heißluftfritteuse 6.2L", text: "€169,99" },
    { alt: "Kaffeevollautomat", imgSrc: "/assets/cloned/images/48512731246e.jpg", href: "https://demo.spreecommerce.org/de/de/products/kaffeevollautomat", title: "Kaffeevollautomat", text: "€819,99" },
    { alt: "Siebträger-Espressomaschine", imgSrc: "/assets/cloned/images/1c316bd76717.jpg", href: "https://demo.spreecommerce.org/de/de/products/siebtrager-espressomaschine", title: "Siebträger-Espressomaschine", text: "€509,99" },
    { alt: "Filterkaffeemaschine 1.5L", imgSrc: "/assets/cloned/images/b41b1840fe0b.jpg", href: "https://demo.spreecommerce.org/de/de/products/filterkaffeemaschine-1-5l", title: "Filterkaffeemaschine 1.5L", text: "€84,99" },
    { alt: "Digitale Heißluftfritteuse 4.2L", imgSrc: "/assets/cloned/images/e5ca3e70300a.jpg", href: "https://demo.spreecommerce.org/de/de/products/digitale-heissluftfritteuse-4-2l", title: "Digitale Heißluftfritteuse 4.2L", text: "€109,99" },
    { alt: "Doppelkorb-Heißluftfritteuse 8L", imgSrc: "/assets/cloned/images/3284c4466783.jpg", href: "https://demo.spreecommerce.org/de/de/products/doppelkorb-heissluftfritteuse-8l", title: "Doppelkorb-Heißluftfritteuse 8L", text: "€229,99" },
    { alt: "Einzelportionsmixer 600ml", imgSrc: "/assets/cloned/images/49f5444df677.jpg", href: "https://demo.spreecommerce.org/de/de/products/einzelportionsmixer-600ml", title: "Einzelportionsmixer 600ml", text: "€46,99" },
    { alt: "Hochleistungsmixer 2.0L", imgSrc: "/assets/cloned/images/5efa1f20c1c2.jpg", href: "https://demo.spreecommerce.org/de/de/products/hochleistungsmixer-2-0l", title: "Hochleistungsmixer 2.0L", text: "€189,99" },
    { alt: "Elektrischer Wasserkocher 1.7L", imgSrc: "/assets/cloned/images/291094e50f28.jpg", href: "https://demo.spreecommerce.org/de/de/products/elektrischer-wasserkocher-1-7l", title: "Elektrischer Wasserkocher 1.7L", text: "€41,99" },
    { alt: "Wasserkocher mit Temperaturwahl 1.7L", imgSrc: "/assets/cloned/images/2387858a2a11.jpg", href: "https://demo.spreecommerce.org/de/de/products/wasserkocher-mit-temperaturwahl-1-7l", title: "Wasserkocher mit Temperaturwahl 1.7L", text: "€74,99" },
    { alt: "2-Scheiben-Toaster", imgSrc: "/assets/cloned/images/63f02400c5c7.jpg", href: "https://demo.spreecommerce.org/de/de/products/2-scheiben-toaster", title: "2-Scheiben-Toaster", text: "€37,99" },
    { alt: "4-Scheiben-Toaster", imgSrc: "/assets/cloned/images/32baa566959f.jpg", href: "https://demo.spreecommerce.org/de/de/products/4-scheiben-toaster", title: "4-Scheiben-Toaster", text: "€59,99" },
    { alt: "Küchenmaschine 3.0L", imgSrc: "/assets/cloned/images/c62802537119.jpg", href: "https://demo.spreecommerce.org/de/de/products/kuchenmaschine-3-0l", title: "Küchenmaschine 3.0L", text: "€139,99" },
    { alt: "Kompakter Luftreiniger", imgSrc: "/assets/cloned/images/add15cc74d3d.jpg", href: "https://demo.spreecommerce.org/de/de/products/kompakter-luftreiniger", title: "Kompakter Luftreiniger", text: "€139,99" },
    { alt: "Turm-Luftreiniger", imgSrc: "/assets/cloned/images/842eb14cbade.jpg", href: "https://demo.spreecommerce.org/de/de/products/turm-luftreiniger", title: "Turm-Luftreiniger", text: "€329,99" },
    { alt: "Luftreiniger Pro", imgSrc: "/assets/cloned/images/c7b04efae94c.jpg", href: "https://demo.spreecommerce.org/de/de/products/luftreiniger-pro", title: "Luftreiniger Pro", text: "€509,99" },
    { alt: "Ultraschall-Luftbefeuchter 2.0L", imgSrc: "/assets/cloned/images/be520bd82481.jpg", href: "https://demo.spreecommerce.org/de/de/products/ultraschall-luftbefeuchter-2-0l", title: "Ultraschall-Luftbefeuchter 2.0L", text: "€64,99" },
    { alt: "Smarter Luftbefeuchter 4.0L", imgSrc: "/assets/cloned/images/5a121afdbe0f.jpg", href: "https://demo.spreecommerce.org/de/de/products/smarter-luftbefeuchter-4-0l", title: "Smarter Luftbefeuchter 4.0L", text: "€119,99" },
    { alt: "Turmventilator 100cm", imgSrc: "/assets/cloned/images/8c2e08e57836.webp", href: "https://demo.spreecommerce.org/de/de/products/turmventilator-100cm", title: "Turmventilator 100cm", text: "€84,99" },
    { alt: "Standventilator 40cm", imgSrc: "/assets/cloned/images/19d70a7056eb.jpg", href: "https://demo.spreecommerce.org/de/de/products/standventilator-40cm", title: "Standventilator 40cm", text: "€54,99" },
    { alt: "Dampfbügelstation", imgSrc: "/assets/cloned/images/0ef6ac1ee67b.jpg", href: "https://demo.spreecommerce.org/de/de/products/dampfbugelstation", title: "Dampfbügelstation", text: "€229,99" },
    { alt: "Handdampfglätter", imgSrc: "/assets/cloned/images/dbba70390666.jpg", href: "https://demo.spreecommerce.org/de/de/products/handdampfglatter", title: "Handdampfglätter", text: "€46,99" }
];
const ProductCard_data2 = [
    { alt: "Dampfbügeleisen 2400W", imgSrc: "/assets/cloned/images/63fb8c02cde1.jpg", href: "https://demo.spreecommerce.org/de/de/products/dampfbugeleisen-2400w", title: "Dampfbügeleisen 2400W", text: "€54,99" },
    { alt: "Kabelloser Stabstaubsauger 18V", imgSrc: "/assets/cloned/images/bef1a42c05a9.jpg", href: "https://demo.spreecommerce.org/de/de/products/kabelloser-stabstaubsauger-18v", title: "Kabelloser Stabstaubsauger 18V", text: "€229,99" },
    { alt: "Kabelloser Stabstaubsauger 25V", imgSrc: "/assets/cloned/images/e1fdc6692aa1.jpg", href: "https://demo.spreecommerce.org/de/de/products/kabelloser-stabstaubsauger-25v", title: "Kabelloser Stabstaubsauger 25V", text: "€419,99" }
];
const ProductCard_data3 = [
    { alt: "Saugroboter", imgSrc: "/assets/cloned/images/80b1177b3083.jpg", href: "https://demo.spreecommerce.org/de/de/products/saugroboter", title: "Saugroboter", text: "€329,99" },
    { alt: "Ionen-Haartrockner 2000W", imgSrc: "/assets/cloned/images/809498c1fc62.jpg", href: "https://demo.spreecommerce.org/de/de/products/ionen-haartrockner-2000w", title: "Ionen-Haartrockner 2000W", text: "€64,99" },
    { alt: "Kompakter Reise-Haartrockner", imgSrc: "/assets/cloned/images/e23e681e40da.jpg", href: "https://demo.spreecommerce.org/de/de/products/kompakter-reise-haartrockner", title: "Kompakter Reise-Haartrockner", text: "€32,99" },
    { alt: "Keramik-Haarglätter", imgSrc: "/assets/cloned/images/efbe2a9902c0.jpg", href: "https://demo.spreecommerce.org/de/de/products/keramik-haarglatter", title: "Keramik-Haarglätter", text: "€74,99" },
    { alt: "Barttrimmer 3000", imgSrc: "/assets/cloned/images/94c4016651be.jpg", href: "https://demo.spreecommerce.org/de/de/products/barttrimmer-3000", title: "Barttrimmer 3000", text: "€46,99" },
    { alt: "Barttrimmer 7000", imgSrc: "/assets/cloned/images/432c84e6c7de.jpg", href: "https://demo.spreecommerce.org/de/de/products/barttrimmer-7000", title: "Barttrimmer 7000", text: "€109,99" },
    { alt: "Multigrooming-Set 10-in-1", imgSrc: "/assets/cloned/images/8b2a8d5c02bb.jpg", href: "https://demo.spreecommerce.org/de/de/products/multigrooming-set-10-in-1", title: "Multigrooming-Set 10-in-1", text: "€74,99" },
    { alt: "Rotationsrasierer 5000", imgSrc: "/assets/cloned/images/e073fba64048.jpg", href: "https://demo.spreecommerce.org/de/de/products/rotationsrasierer-5000", title: "Rotationsrasierer 5000", text: "€119,99" },
    { alt: "Rotationsrasierer 9000", imgSrc: "/assets/cloned/images/8687a8347d94.jpg", href: "https://demo.spreecommerce.org/de/de/products/rotationsrasierer-9000", title: "Rotationsrasierer 9000", text: "€279,99" }
];
const NavigationLink_data3 = [
    { href: "/de/de/products", label: "Alle Produkte" },
    { href: "/de/de/c/kitchen", label: "Küche" },
    { href: "https://demo.spreecommerce.org/de/de/c/air-and-climate", label: "Luft & Klima" },
    { href: "https://demo.spreecommerce.org/de/de/c/garment-care", label: "Kleidungspflege" },
    { href: "https://demo.spreecommerce.org/de/de/c/floor-care", label: "Bodenpflege" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care", label: "Körperpflege" }
];
const NavigationLink_data4 = [
    { href: "https://demo.spreecommerce.org/de/de/account", label: "Mein Konto" },
    { href: "https://demo.spreecommerce.org/de/de/account/orders", label: "Bestellverlauf" },
    { href: "/de/de/cart", label: "Warenkorb" },
    { href: "https://demo.spreecommerce.org/de/de/wholesale", label: "Handel & Großhandel" }
];
const NavigationLink_data5 = [
    { href: "https://demo.spreecommerce.org/de/de/policies/shipping-policy", label: "Versandrichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/privacy-policy", label: "Datenschutzrichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/returns-policy", label: "Rückgaberichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/terms-of-service", label: "Nutzungsbedingungen" }
];
const NavigationLink_cids: string[][] = [
    ["n43", "n44"],
    ["n45", "n46"],
    ["n47", "n48"],
    ["n49", "n50"],
    ["n51", "n52"],
    ["n53", "n54"]
];
const MegaMenuCategory_cids: string[][] = [
    ["n55", "n56", "n57", "n58", "n59", "n60", "n61", "n62", "n63"],
    ["n64", "n65", "n66", "n67", "n68", "n69", "n70", "n71", "n72"],
    ["n73", "n74", "n75", "n76", "n77", "n78", "n79", "n80", "n81"]
];
const NavigationLink_cids2: string[][] = [
    ["n85", "n86"],
    ["n87", "n88"],
    ["n89", "n90"],
    ["n91", "n92"]
];
const FilterMenuTrigger_cids: string[][] = [
    ["n102", "n103", "n104"],
    ["n105", "n106", "n107"],
    ["n108", "n109", "n110"]
];
const ProductCard_cids: string[][] = [
    ["n125", "n126", "n127", "n128", "n129", "n130", "n131", "n132"],
    ["n133", "n134", "n135", "n136", "n137", "n138", "n139", "n140"],
    ["n141", "n142", "n143", "n144", "n145", "n146", "n147", "n148"],
    ["n149", "n150", "n151", "n152", "n153", "n154", "n155", "n156"],
    ["n157", "n158", "n159", "n160", "n161", "n162", "n163", "n164"],
    ["n165", "n166", "n167", "n168", "n169", "n170", "n171", "n172"],
    ["n173", "n174", "n175", "n176", "n177", "n178", "n179", "n180"],
    ["n181", "n182", "n183", "n184", "n185", "n186", "n187", "n188"],
    ["n189", "n190", "n191", "n192", "n193", "n194", "n195", "n196"],
    ["n197", "n198", "n199", "n200", "n201", "n202", "n203", "n204"],
    ["n205", "n206", "n207", "n208", "n209", "n210", "n211", "n212"],
    ["n213", "n214", "n215", "n216", "n217", "n218", "n219", "n220"],
    ["n221", "n222", "n223", "n224", "n225", "n226", "n227", "n228"],
    ["n229", "n230", "n231", "n232", "n233", "n234", "n235", "n236"],
    ["n237", "n238", "n239", "n240", "n241", "n242", "n243", "n244"],
    ["n245", "n246", "n247", "n248", "n249", "n250", "n251", "n252"],
    ["n253", "n254", "n255", "n256", "n257", "n258", "n259", "n260"],
    ["n261", "n262", "n263", "n264", "n265", "n266", "n267", "n268"],
    ["n269", "n270", "n271", "n272", "n273", "n274", "n275", "n276"],
    ["n277", "n278", "n279", "n280", "n281", "n282", "n283", "n284"],
    ["n285", "n286", "n287", "n288", "n289", "n290", "n291", "n292"],
    ["n293", "n294", "n295", "n296", "n297", "n298", "n299", "n300"]
];
const ProductCard_cids2: string[][] = [
    ["n311", "n312", "n313", "n314", "n315", "n316", "n317", "n318"],
    ["n319", "n320", "n321", "n322", "n323", "n324", "n325", "n326"],
    ["n327", "n328", "n329", "n330", "n331", "n332", "n333", "n334"]
];
const ProductCard_cids3: string[][] = [
    ["n345", "n346", "n347", "n348", "n349", "n350", "n351", "n352"],
    ["n353", "n354", "n355", "n356", "n357", "n358", "n359", "n360"],
    ["n361", "n362", "n363", "n364", "n365", "n366", "n367", "n368"],
    ["n369", "n370", "n371", "n372", "n373", "n374", "n375", "n376"],
    ["n377", "n378", "n379", "n380", "n381", "n382", "n383", "n384"],
    ["n385", "n386", "n387", "n388", "n389", "n390", "n391", "n392"],
    ["n393", "n394", "n395", "n396", "n397", "n398", "n399", "n400"],
    ["n401", "n402", "n403", "n404", "n405", "n406", "n407", "n408"],
    ["n409", "n410", "n411", "n412", "n413", "n414", "n415", "n416"]
];
const NavigationLink_cids3: string[][] = [
    ["n432", "n433"],
    ["n434", "n435"],
    ["n436", "n437"],
    ["n438", "n439"],
    ["n440", "n441"],
    ["n442", "n443"]
];
const NavigationLink_cids4: string[][] = [
    ["n447", "n448"],
    ["n449", "n450"],
    ["n451", "n452"],
    ["n453", "n454"]
];
const NavigationLink_cids5: string[][] = [
    ["n458", "n459"],
    ["n460", "n461"],
    ["n462", "n463"],
    ["n464", "n465"]
];
const NavigationLink_styles = [
    { className: "cn43", className2: "cn44" },
    { className: "cn45", className2: "cn46" },
    { className: "cn47", className2: "cn48" },
    { className: "cn49", className2: "cn50" },
    { className: "cn51", className2: "cn52" },
    { className: "cn53", className2: "cn54" }
];
const MegaMenuCategory_styles = [
    { className: "cn55", className2: "cn56", className3: "cn57", className4: "cn58", className5: "cn59", className6: "cn60", className7: "cn61", className8: "cn62", className9: "cn63" },
    { className: "cn64", className2: "cn65", className3: "cn66", className4: "cn67", className5: "cn68", className6: "cn69", className7: "cn70", className8: "cn71", className9: "cn72" },
    { className: "cn73", className2: "cn74", className3: "cn75", className4: "cn76", className5: "cn77", className6: "cn78", className7: "cn79", className8: "cn80", className9: "cn81" }
];
const NavigationLink_styles2 = [
    { className: "cn85", className2: "cn86" },
    { className: "cn87", className2: "cn88" },
    { className: "cn89", className2: "cn90" },
    { className: "cn91", className2: "cn92" }
];
const FilterMenuTrigger_styles = [
    { className: "cn102", className2: "cn103", className3: "cn104" },
    { className: "cn105", className2: "cn106", className3: "cn107" },
    { className: "cn108", className2: "cn109", className3: "cn110" }
];
const ProductCard_styles = [
    { className: "cn125", className2: "cn126", className3: "cn127", className4: "cn128", className5: "cn129", className6: "cn130", className7: "cn131", className8: "cn132" },
    { className: "cn133", className2: "cn134", className3: "cn135", className4: "cn136", className5: "cn137", className6: "cn138", className7: "cn139", className8: "cn140" },
    { className: "cn141", className2: "cn142", className3: "cn143", className4: "cn144", className5: "cn145", className6: "cn146", className7: "cn147", className8: "cn148" },
    { className: "cn149", className2: "cn150", className3: "cn151", className4: "cn152", className5: "cn153", className6: "cn154", className7: "cn155", className8: "cn156" },
    { className: "cn157", className2: "cn158", className3: "cn159", className4: "cn160", className5: "cn161", className6: "cn162", className7: "cn163", className8: "cn164" },
    { className: "cn165", className2: "cn166", className3: "cn167", className4: "cn168", className5: "cn169", className6: "cn170", className7: "cn171", className8: "cn172" },
    { className: "cn173", className2: "cn174", className3: "cn175", className4: "cn176", className5: "cn177", className6: "cn178", className7: "cn179", className8: "cn180" },
    { className: "cn181", className2: "cn182", className3: "cn183", className4: "cn184", className5: "cn185", className6: "cn186", className7: "cn187", className8: "cn188" },
    { className: "cn189", className2: "cn190", className3: "cn191", className4: "cn192", className5: "cn193", className6: "cn194", className7: "cn195", className8: "cn196" },
    { className: "cn197", className2: "cn198", className3: "cn199", className4: "cn200", className5: "cn201", className6: "cn202", className7: "cn203", className8: "cn204" },
    { className: "cn205", className2: "cn206", className3: "cn207", className4: "cn208", className5: "cn209", className6: "cn210", className7: "cn211", className8: "cn212" },
    { className: "cn213", className2: "cn214", className3: "cn215", className4: "cn216", className5: "cn217", className6: "cn218", className7: "cn219", className8: "cn220" },
    { className: "cn221", className2: "cn222", className3: "cn223", className4: "cn224", className5: "cn225", className6: "cn226", className7: "cn227", className8: "cn228" },
    { className: "cn229", className2: "cn230", className3: "cn231", className4: "cn232", className5: "cn233", className6: "cn234", className7: "cn235", className8: "cn236" },
    { className: "cn237", className2: "cn238", className3: "cn239", className4: "cn240", className5: "cn241", className6: "cn242", className7: "cn243", className8: "cn244" },
    { className: "cn245", className2: "cn246", className3: "cn247", className4: "cn248", className5: "cn249", className6: "cn250", className7: "cn251", className8: "cn252" },
    { className: "cn253", className2: "cn254", className3: "cn255", className4: "cn256", className5: "cn257", className6: "cn258", className7: "cn259", className8: "cn260" },
    { className: "cn261", className2: "cn262", className3: "cn263", className4: "cn264", className5: "cn265", className6: "cn266", className7: "cn267", className8: "cn268" },
    { className: "cn269", className2: "cn270", className3: "cn271", className4: "cn272", className5: "cn273", className6: "cn274", className7: "cn275", className8: "cn276" },
    { className: "cn277", className2: "cn278", className3: "cn279", className4: "cn280", className5: "cn281", className6: "cn282", className7: "cn283", className8: "cn284" },
    { className: "cn285", className2: "cn286", className3: "cn287", className4: "cn288", className5: "cn289", className6: "cn290", className7: "cn291", className8: "cn292" },
    { className: "cn293", className2: "cn294", className3: "cn295", className4: "cn296", className5: "cn297", className6: "cn298", className7: "cn299", className8: "cn300" }
];
const ProductCard_styles2 = [
    { className: "cn311", className2: "cn312", className3: "cn313", className4: "cn314", className5: "cn315", className6: "cn316", className7: "cn317", className8: "cn318" },
    { className: "cn319", className2: "cn320", className3: "cn321", className4: "cn322", className5: "cn323", className6: "cn324", className7: "cn325", className8: "cn326" },
    { className: "cn327", className2: "cn328", className3: "cn329", className4: "cn330", className5: "cn331", className6: "cn332", className7: "cn333", className8: "cn334" }
];
const ProductCard_styles3 = [
    { className: "cn345", className2: "cn346", className3: "cn347", className4: "cn348", className5: "cn349", className6: "cn350", className7: "cn351", className8: "cn352" },
    { className: "cn353", className2: "cn354", className3: "cn355", className4: "cn356", className5: "cn357", className6: "cn358", className7: "cn359", className8: "cn360" },
    { className: "cn361", className2: "cn362", className3: "cn363", className4: "cn364", className5: "cn365", className6: "cn366", className7: "cn367", className8: "cn368" },
    { className: "cn369", className2: "cn370", className3: "cn371", className4: "cn372", className5: "cn373", className6: "cn374", className7: "cn375", className8: "cn376" },
    { className: "cn377", className2: "cn378", className3: "cn379", className4: "cn380", className5: "cn381", className6: "cn382", className7: "cn383", className8: "cn384" },
    { className: "cn385", className2: "cn386", className3: "cn387", className4: "cn388", className5: "cn389", className6: "cn390", className7: "cn391", className8: "cn392" },
    { className: "cn393", className2: "cn394", className3: "cn395", className4: "cn396", className5: "cn397", className6: "cn398", className7: "cn399", className8: "cn400" },
    { className: "cn401", className2: "cn402", className3: "cn403", className4: "cn404", className5: "cn405", className6: "cn406", className7: "cn407", className8: "cn408" },
    { className: "cn409", className2: "cn410", className3: "cn411", className4: "cn412", className5: "cn413", className6: "cn414", className7: "cn415", className8: "cn416" }
];
const NavigationLink_styles3 = [
    { className: "cn432", className2: "cn433" },
    { className: "cn434", className2: "cn435" },
    { className: "cn436", className2: "cn437" },
    { className: "cn438", className2: "cn439" },
    { className: "cn440", className2: "cn441" },
    { className: "cn442", className2: "cn443" }
];
const NavigationLink_styles4 = [
    { className: "cn447", className2: "cn448" },
    { className: "cn449", className2: "cn450" },
    { className: "cn451", className2: "cn452" },
    { className: "cn453", className2: "cn454" }
];
const NavigationLink_styles5 = [
    { className: "cn458", className2: "cn459" },
    { className: "cn460", className2: "cn461" },
    { className: "cn462", className2: "cn463" },
    { className: "cn464", className2: "cn465" }
];

export default function Page() {
  return (
    <>
      <StorefrontHeader className="cn1" data-cid="n1">
        <div className="cn2" data-cid="n2">
          <div className="cn3" data-cid="n3">
            <div className="cn4" data-cid="n4">
              <div className="cn5" data-cid="n5">
                <button className="cn6" data-cid="n6" data-component="button" aria-label="Menü öffnen">
                  <div className="cn7" data-cid="n7">
                    <span className="cn8" data-cid="n8" />
                    <span className="cn9" data-cid="n9" />
                    <span className="cn10" data-cid="n10" />
                  </div>
                </button>
              </div>
              <div className="cn11" data-cid="n11">
                <a className="cn12" data-cid="n12" data-component="link" href="/de/de">
                  <img className="cn13" data-cid="n13" data-component="image" alt="Spree" height="32" src="/assets/cloned/images/ccdab56ac016.png" width="90" />
                </a>
              </div>
              <div className="cn14" data-cid="n14">
                <div className="cn15" data-cid="n15">
                  <a className="cn16" data-cid="n16" data-component="link" href="https://demo.spreecommerce.org/de/de/wholesale">
                    Großhandel
                  </a>
                  <button className="cn17" data-cid="n17" data-component="button" aria-controls="radix-_R_579iujpfivb_" aria-expanded="false" aria-haspopup="dialog" aria-label="Region und Sprache" type="button">
                    <span className="cn18" data-cid="n18" aria-hidden="true">
                      <img className="cn19" data-cid="n19" data-component="image" alt="" height="18" src="/assets/cloned/svg/2c32e09c2f97.svg" width="18" />
                    </span>
                  </button>
                </div>
                <button className="cn20" data-cid="n20" data-component="button" aria-controls="search-overlay" aria-expanded="false" aria-label="Suche öffnen">
                  <svg className="cn21" data-cid="n21" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="m21 21-4.34-4.34" />
                    <circle cx="11" cy="11" r="8" />
                  </svg>
                </button>
                <div className="cn22" data-cid="n22">
                  <a className="cn23" data-cid="n23" data-component="link" aria-label="Konto" href="https://demo.spreecommerce.org/de/de/account">
                    <svg className="cn24" data-cid="n24" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                      <circle cx="12" cy="7" r="4" />
                    </svg>
                  </a>
                </div>
                <button className="cn25" data-cid="n25" data-component="button" aria-label="Warenkorb öffnen">
                  <svg className="cn26" data-cid="n26" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 10a4 4 0 0 1-8 0" />
                    <path d="M3.103 6.034h17.794" />
                    <path d="M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="cn27" data-cid="n27" id="search-overlay">
          <div className="cn28" data-cid="n28">
            <div className="cn29" data-cid="n29">
              <div className="cn30" data-cid="n30">
                <form className="cn31" data-cid="n31">
                  <div className="cn32" data-cid="n32" role="group">
                    <input className="cn33" data-cid="n33" data-component="select" aria-autocomplete="list" aria-controls="search-suggestions" aria-expanded="false" aria-label="Suche..." placeholder="Suche..." role="combobox" type="search" value="" />
                    <div className="cn34" data-cid="n34" role="group">
                      <svg className="cn35" data-cid="n35" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="m21 21-4.34-4.34" />
                        <circle cx="11" cy="11" r="8" />
                      </svg>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <button className="cn36" data-cid="n36" data-component="button" aria-label="Suche schließen">
              <svg className="cn37" data-cid="n37" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M18 6 6 18" />
                <path d="m6 6 12 12" />
              </svg>
            </button>
          </div>
        </div>
      </StorefrontHeader>
      <nav className="cn38" data-cid="n38" aria-label="Category navigation">
        <ul className="cn39" data-cid="n39">
          <li className="cn40" data-cid="n40">
            <a className="cn41" data-cid="n41" data-component="link" href="/de/de/c/kitchen">
              Küche
            </a>
            <ul className="cn42" data-cid="n42">
              {NavigationLink_data.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids[i]} styles={NavigationLink_styles[i]} />)}
            </ul>
          </li>
          {MegaMenuCategory_data.map((d, i) => <MegaMenuCategory key={i} d={d} cids={MegaMenuCategory_cids[i]} styles={MegaMenuCategory_styles[i]} />)}
          <li className="cn82" data-cid="n82">
            <a className="cn83" data-cid="n83" data-component="link" href="https://demo.spreecommerce.org/de/de/c/personal-care">
              Körperpflege
            </a>
            <ul className="cn84" data-cid="n84">
              {NavigationLink_data2.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids2[i]} styles={NavigationLink_styles2[i]} />)}
            </ul>
          </li>
        </ul>
      </nav>
      <main className="cn93" data-cid="n93">
        <div className="cn94" data-cid="n94">
          <div className="cn95" data-cid="n95">
            <h1 className="cn96" data-cid="n96" data-component="heading">
              Alle Produkte
            </h1>
            <p className="cn97" data-cid="n97">
              Entdecken Sie unsere gesamte Kollektion
            </p>
          </div>
          <div className="cn98" data-cid="n98" aria-busy="false">
            <div className="cn99" data-cid="n99">
              <div className="cn100" data-cid="n100">
                <div className="cn101" data-cid="n101">
                  {FilterMenuTrigger_data.map((d, i) => <FilterMenuTrigger key={i} d={d} cids={FilterMenuTrigger_cids[i]} styles={FilterMenuTrigger_styles[i]} />)}
                </div>
                <div className="cn111" data-cid="n111">
                  <span className="cn112" data-cid="n112">
                    36 Produkte
                  </span>
                  <button className="cn113" data-cid="n113" data-component="button" aria-expanded="false" aria-haspopup="menu" id="radix-_R_2hclubriujpfivb_" type="button">
                    <span className="cn114" data-cid="n114">
                      Sortieren
                    </span>
                    <svg className="cn115" data-cid="n115" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="m6 9 6 6 6-6" />
                    </svg>
                  </button>
                </div>
              </div>
              <div className="cn116" data-cid="n116">
                <button className="cn117" data-cid="n117" type="button">
                  <svg className="cn118" data-cid="n118" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M10 5H3" />
                    <path d="M12 19H3" />
                    <path d="M14 3v4" />
                    <path d="M16 17v4" />
                    <path d="M21 12h-9" />
                    <path d="M21 19h-5" />
                    <path d="M21 5h-7" />
                    <path d="M8 10v4" />
                    <path d="M8 12H3" />
                  </svg>
                  <span className="cn119" data-cid="n119">
                    Filter
                  </span>
                </button>
                <div className="cn120" data-cid="n120">
                  <button className="cn121" data-cid="n121" aria-expanded="false" aria-haspopup="menu" id="radix-_R_iclubriujpfivb_" type="button">
                    <span className="cn122" data-cid="n122">
                      Sortieren
                    </span>
                    <svg className="cn123" data-cid="n123" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="m6 9 6 6 6-6" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div className="cn124" data-cid="n124">
            {ProductCard_data.map((d, i) => <ProductCard key={i} d={d} cids={ProductCard_cids[i]} styles={ProductCard_styles[i]} />)}
            <div className="cn301" data-cid="n301">
              <div className="cn302" data-cid="n302">
                <img className="cn303" data-cid="n303" data-component="image" alt="Professioneller Dampfglätter" height="304" src="/assets/cloned/images/3585c22126bd.webp" width="304" />
                <span className="cn304" data-cid="n304">
                  Sale
                </span>
              </div>
              <div className="cn305" data-cid="n305">
                <h3 className="cn306" data-cid="n306" data-component="heading">
                  <a className="cn307" data-cid="n307" data-component="link" href="https://demo.spreecommerce.org/de/de/products/professioneller-dampfglatter">
                    Professioneller Dampfglätter
                  </a>
                </h3>
                <div className="cn308" data-cid="n308">
                  <span className="cn309" data-cid="n309">
                    €95,00
                  </span>
                  <span className="cn310" data-cid="n310">
                    €119,99
                  </span>
                </div>
              </div>
            </div>
            {ProductCard_data2.map((d, i) => <ProductCard key={i} d={d} cids={ProductCard_cids2[i]} styles={ProductCard_styles2[i]} />)}
            <div className="cn335" data-cid="n335">
              <div className="cn336" data-cid="n336">
                <img className="cn337" data-cid="n337" data-component="image" alt="Beutelloser Standstaubsauger" height="304" src="/assets/cloned/images/64e63b477575.jpg" width="304" />
                <span className="cn338" data-cid="n338">
                  Sale
                </span>
              </div>
              <div className="cn339" data-cid="n339">
                <h3 className="cn340" data-cid="n340" data-component="heading">
                  <a className="cn341" data-cid="n341" data-component="link" href="https://demo.spreecommerce.org/de/de/products/beutelloser-standstaubsauger">
                    Beutelloser Standstaubsauger
                  </a>
                </h3>
                <div className="cn342" data-cid="n342">
                  <span className="cn343" data-cid="n343">
                    €140,00
                  </span>
                  <span className="cn344" data-cid="n344">
                    €189,99
                  </span>
                </div>
              </div>
            </div>
            {ProductCard_data3.map((d, i) => <ProductCard key={i} d={d} cids={ProductCard_cids3[i]} styles={ProductCard_styles3[i]} />)}
          </div>
          <div className="cn417" data-cid="n417">
            <p className="cn418" data-cid="n418">
              Keine weiteren Produkte zum Laden
            </p>
          </div>
        </div>
      </main>
      <StorefrontFooter className="cn419" data-cid="n419">
        <div className="cn420" data-cid="n420">
          <div className="cn421" data-cid="n421">
            <div className="cn422" data-cid="n422">
              <span className="cn423" data-cid="n423">
                Spree
              </span>
              <p className="cn424" data-cid="n424">
                Open-Source-E-Commerce basierend auf Spree REST API, TypeScript SDK und Next.js. Selbst hosten. Eigene Daten. Keine Plattformgebühren.
              </p>
              <div className="cn425" data-cid="n425">
                <a className="cn426" data-cid="n426" data-component="link" href="https://github.com/spree/storefront" rel="noopener noreferrer" target="_blank">
                  Diese Storefront auf GitHub forken→
                </a>
                <a className="cn427" data-cid="n427" data-component="link" href="https://spreecommerce.org/docs/developer/getting-started/quickstart" rel="noopener noreferrer" target="_blank">
                  Schnellstartanleitung
                </a>
                <a className="cn428" data-cid="n428" data-component="link" href="https://spreecommerce.org/" rel="noopener noreferrer" target="_blank">
                  Mehr über Spree Commerce erfahren
                </a>
              </div>
            </div>
            <div className="cn429" data-cid="n429">
              <h3 className="cn430" data-cid="n430" data-component="heading">
                Shop
              </h3>
              <ul className="cn431" data-cid="n431">
                {NavigationLink_data3.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids3[i]} styles={NavigationLink_styles3[i]} />)}
              </ul>
            </div>
            <div className="cn444" data-cid="n444">
              <h3 className="cn445" data-cid="n445" data-component="heading">
                Konto
              </h3>
              <ul className="cn446" data-cid="n446">
                {NavigationLink_data4.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids4[i]} styles={NavigationLink_styles4[i]} />)}
              </ul>
            </div>
            <div className="cn455" data-cid="n455">
              <h3 className="cn456" data-cid="n456" data-component="heading">
                Richtlinien
              </h3>
              <ul className="cn457" data-cid="n457">
                {NavigationLink_data5.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids5[i]} styles={NavigationLink_styles5[i]} />)}
              </ul>
            </div>
          </div>
          <div className="cn466" data-cid="n466">
            <p className="cn467" data-cid="n467">
              {"© 2026 Spree. Betrieben von "}
              <a className="cn468" data-cid="n468" data-component="link" href="https://spreecommerce.org/" target="_blank">
                Spree Commerce
              </a>
              {" & Next.js."}
            </p>
          </div>
        </div>
      </StorefrontFooter>
      <section className="cn469" data-cid="n469" aria-atomic="false" aria-label="Notifications alt+T" aria-live="polite" aria-relevant="additions text" />
    </>
  );
}
