import { StorefrontHeader, StorefrontFooter } from "../../storefront/StorefrontChrome";
import "./ditto.css";
import NavigationLink from "./components/navigation-link";
import MegaMenuCategory from "./components/mega-menu-category";
import ProductCard from "./components/product-card";
import CommerceBenefitCard from "./components/commerce-benefit-card";
// Generated by clone-site. Do not edit by hand.
const NavigationLink_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kaffeemaschinen", label: "Kaffeemaschinen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/heissluftfritteusen", label: "Heißluftfritteusen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/mixer", label: "Mixer" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/wasserkocher", label: "Wasserkocher" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/toaster", label: "Toaster" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kuchenmaschinen", label: "Küchenmaschinen" }
];
const MegaMenuCategory_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/air-and-climate", label: "Luft & Klima", href2: "https://demo.spreecommerce.org/de/de/c/air-and-climate/luftreiniger", label2: "Luftreiniger", href3: "https://demo.spreecommerce.org/de/de/c/air-and-climate/luftbefeuchter", label3: "Luftbefeuchter", href4: "https://demo.spreecommerce.org/de/de/c/air-and-climate/ventilator", label4: "Ventilator" },
    { href: "https://demo.spreecommerce.org/de/de/c/garment-care", label: "Kleidungspflege", href2: "https://demo.spreecommerce.org/de/de/c/garment-care/dampferzeuger", label2: "Dampferzeuger", href3: "https://demo.spreecommerce.org/de/de/c/garment-care/handdampfreiniger", label3: "Handdampfreiniger", href4: "https://demo.spreecommerce.org/de/de/c/garment-care/bugeleisen", label4: "Bügeleisen" },
    { href: "https://demo.spreecommerce.org/de/de/c/floor-care", label: "Bodenpflege", href2: "https://demo.spreecommerce.org/de/de/c/floor-care/akku-staubsauger", label2: "Akku-Staubsauger", href3: "https://demo.spreecommerce.org/de/de/c/floor-care/saugroboter", label3: "Saugroboter", href4: "https://demo.spreecommerce.org/de/de/c/floor-care/aufrechte-staubsauger", label4: "Aufrechte Staubsauger" }
];
const NavigationLink_data2 = [
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haartrockner", label: "Haartrockner" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haarglatter", label: "Haarglätter" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haartrimmer", label: "Haartrimmer" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/elektrorasierer", label: "Elektrorasierer" }
];
const ProductCard_data = [
    { kind: "image", alt: "Digitale Heißluftfritteuse 6.2L", height: "214", imgSrc: "/assets/cloned/images/4467de6bff7e.jpg", width: "214", kind2: "heading", kind3: "link", href: "/de/de/products/digitale-heissluftfritteuse-6-2l", title: "Digitale Heißluftfritteuse 6.2L", text: "€169,99" },
    { kind: "image", alt: "Kaffeevollautomat", height: "214", imgSrc: "/assets/cloned/images/48512731246e.jpg", width: "214", kind2: "heading", kind3: "link", href: "https://demo.spreecommerce.org/de/de/products/kaffeevollautomat", title: "Kaffeevollautomat", text: "€819,99" },
    { kind: "image", alt: "Siebträger-Espressomaschine", height: "214", imgSrc: "/assets/cloned/images/1c316bd76717.jpg", width: "214", kind2: "heading", kind3: "link", href: "https://demo.spreecommerce.org/de/de/products/siebtrager-espressomaschine", title: "Siebträger-Espressomaschine", text: "€509,99" },
    { kind: "image", alt: "Filterkaffeemaschine 1.5L", height: "214", imgSrc: "/assets/cloned/images/b41b1840fe0b.jpg", width: "214", kind2: "heading", kind3: "link", href: "https://demo.spreecommerce.org/de/de/products/filterkaffeemaschine-1-5l", title: "Filterkaffeemaschine 1.5L", text: "€84,99" },
    { kind: "image", alt: "Digitale Heißluftfritteuse 4.2L", height: "214", imgSrc: "/assets/cloned/images/e5ca3e70300a.jpg", width: "214", kind2: "heading", kind3: "link", href: "https://demo.spreecommerce.org/de/de/products/digitale-heissluftfritteuse-4-2l", title: "Digitale Heißluftfritteuse 4.2L", text: "€109,99" },
    { kind: "image", alt: "Doppelkorb-Heißluftfritteuse 8L", height: "214", imgSrc: "/assets/cloned/images/3284c4466783.jpg", width: "214", href: "https://demo.spreecommerce.org/de/de/products/doppelkorb-heissluftfritteuse-8l", title: "Doppelkorb-Heißluftfritteuse 8L", text: "€229,99" },
    { alt: "Einzelportionsmixer 600ml", height: "214", imgSrc: "/assets/cloned/images/49f5444df677.jpg", width: "214", href: "https://demo.spreecommerce.org/de/de/products/einzelportionsmixer-600ml", title: "Einzelportionsmixer 600ml", text: "€46,99" },
    { alt: "Hochleistungsmixer 2.0L", imgSrc: "/assets/cloned/images/5efa1f20c1c2.jpg", href: "https://demo.spreecommerce.org/de/de/products/hochleistungsmixer-2-0l", title: "Hochleistungsmixer 2.0L", text: "€189,99" }
];
const CommerceBenefitCard_data = [
    { title: "Handelspreise", description: "Ihre ausgehandelten Konditionen werden automatisch auf den gesamten Katalog angewendet." },
    { title: "Schnelle Sammelbestellung", description: "Geben Sie SKUs und Mengen ein, um in Sekunden eine große Bestellung zusammenzustellen." },
    { title: "Bestellverlauf", description: "Sehen Sie vergangene Bestellungen ein und bestellen Sie Ihre Standardartikel mit wenigen Klicks nach." }
];
const NavigationLink_data3 = [
    { href: "/de/de/products", label: "Alle Produkte" },
    { href: "/de/de/c/kitchen", label: "Küche" },
    { href: "https://demo.spreecommerce.org/de/de/c/air-and-climate", label: "Luft & Klima" },
    { href: "https://demo.spreecommerce.org/de/de/c/garment-care", label: "Kleidungspflege" },
    { href: "https://demo.spreecommerce.org/de/de/c/floor-care", label: "Bodenpflege" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care", label: "Körperpflege" }
];
const NavigationLink_data4 = [
    { href: "https://demo.spreecommerce.org/de/de/account", label: "Mein Konto" },
    { href: "https://demo.spreecommerce.org/de/de/account/orders", label: "Bestellverlauf" },
    { href: "/de/de/cart", label: "Warenkorb" },
    { href: "https://demo.spreecommerce.org/de/de/wholesale", label: "Handel & Großhandel" }
];
const NavigationLink_data5 = [
    { href: "https://demo.spreecommerce.org/de/de/policies/shipping-policy", label: "Versandrichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/privacy-policy", label: "Datenschutzrichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/returns-policy", label: "Rückgaberichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/terms-of-service", label: "Nutzungsbedingungen" }
];
const NavigationLink_cids: string[][] = [
    ["n43", "n44"],
    ["n45", "n46"],
    ["n47", "n48"],
    ["n49", "n50"],
    ["n51", "n52"],
    ["n53", "n54"]
];
const MegaMenuCategory_cids: string[][] = [
    ["n55", "n56", "n57", "n58", "n59", "n60", "n61", "n62", "n63"],
    ["n64", "n65", "n66", "n67", "n68", "n69", "n70", "n71", "n72"],
    ["n73", "n74", "n75", "n76", "n77", "n78", "n79", "n80", "n81"]
];
const NavigationLink_cids2: string[][] = [
    ["n85", "n86"],
    ["n87", "n88"],
    ["n89", "n90"],
    ["n91", "n92"]
];
const ProductCard_cids: string[][] = [
    ["n115", "n116", "n117", "n118", "n119", "n120", "n121", "n122", "n123"],
    ["n124", "n125", "n126", "n127", "n128", "n129", "n130", "n131", "n132"],
    ["n133", "n134", "n135", "n136", "n137", "n138", "n139", "n140", "n141"],
    ["n142", "n143", "n144", "n145", "n146", "n147", "n148", "n149", "n150"],
    ["n151", "n152", "n153", "n154", "n155", "n156", "n157", "n158", "n159"],
    ["n160", "n161", "n162", "n163", "n164", "n165", "n166", "n167", "n168"],
    ["n169", "n170", "n171", "n172", "n173", "n174", "n175", "n176", "n177"],
    ["n178", "n179", "n180", "n181", "n182", "n183", "n184", "n185", "n186"]
];
const CommerceBenefitCard_cids: string[][] = [
    ["n198", "n199", "n200"],
    ["n201", "n202", "n203"],
    ["n204", "n205", "n206"]
];
const NavigationLink_cids3: string[][] = [
    ["n220", "n221"],
    ["n222", "n223"],
    ["n224", "n225"],
    ["n226", "n227"],
    ["n228", "n229"],
    ["n230", "n231"]
];
const NavigationLink_cids4: string[][] = [
    ["n235", "n236"],
    ["n237", "n238"],
    ["n239", "n240"],
    ["n241", "n242"]
];
const NavigationLink_cids5: string[][] = [
    ["n246", "n247"],
    ["n248", "n249"],
    ["n250", "n251"],
    ["n252", "n253"]
];
const NavigationLink_styles = [
    { className: "cn43", className2: "cn44" },
    { className: "cn45", className2: "cn46" },
    { className: "cn47", className2: "cn48" },
    { className: "cn49", className2: "cn50" },
    { className: "cn51", className2: "cn52" },
    { className: "cn53", className2: "cn54" }
];
const MegaMenuCategory_styles = [
    { className: "cn55", className2: "cn56", className3: "cn57", className4: "cn58", className5: "cn59", className6: "cn60", className7: "cn61", className8: "cn62", className9: "cn63" },
    { className: "cn64", className2: "cn65", className3: "cn66", className4: "cn67", className5: "cn68", className6: "cn69", className7: "cn70", className8: "cn71", className9: "cn72" },
    { className: "cn73", className2: "cn74", className3: "cn75", className4: "cn76", className5: "cn77", className6: "cn78", className7: "cn79", className8: "cn80", className9: "cn81" }
];
const NavigationLink_styles2 = [
    { className: "cn85", className2: "cn86" },
    { className: "cn87", className2: "cn88" },
    { className: "cn89", className2: "cn90" },
    { className: "cn91", className2: "cn92" }
];
const ProductCard_styles = [
    { className: "cn115", className2: "cn116", className3: "cn117", className4: "cn118", className5: "cn119", className6: "cn120", className7: "cn121", className8: "cn122", className9: "cn123" },
    { className: "cn124", className2: "cn125", className3: "cn126", className4: "cn127", className5: "cn128", className6: "cn129", className7: "cn130", className8: "cn131", className9: "cn132" },
    { className: "cn133", className2: "cn134", className3: "cn135", className4: "cn136", className5: "cn137", className6: "cn138", className7: "cn139", className8: "cn140", className9: "cn141" },
    { className: "cn142", className2: "cn143", className3: "cn144", className4: "cn145", className5: "cn146", className6: "cn147", className7: "cn148", className8: "cn149", className9: "cn150" },
    { className: "cn151", className2: "cn152", className3: "cn153", className4: "cn154", className5: "cn155", className6: "cn156", className7: "cn157", className8: "cn158", className9: "cn159" },
    { className: "cn160", className2: "cn161", className3: "cn162", className4: "cn163", className5: "cn164", className6: "cn165", className7: "cn166", className8: "cn167", className9: "cn168" },
    { className: "cn169", className2: "cn170", className3: "cn171", className4: "cn172", className5: "cn173", className6: "cn174", className7: "cn175", className8: "cn176", className9: "cn177" },
    { className: "cn178", className2: "cn179", className3: "cn180", className4: "cn181", className5: "cn182", className6: "cn183", className7: "cn184", className8: "cn185", className9: "cn186" }
];
const CommerceBenefitCard_styles = [
    { className: "cn198", className2: "cn199", className3: "cn200" },
    { className: "cn201", className2: "cn202", className3: "cn203" },
    { className: "cn204", className2: "cn205", className3: "cn206" }
];
const NavigationLink_styles3 = [
    { className: "cn220", className2: "cn221" },
    { className: "cn222", className2: "cn223" },
    { className: "cn224", className2: "cn225" },
    { className: "cn226", className2: "cn227" },
    { className: "cn228", className2: "cn229" },
    { className: "cn230", className2: "cn231" }
];
const NavigationLink_styles4 = [
    { className: "cn235", className2: "cn236" },
    { className: "cn237", className2: "cn238" },
    { className: "cn239", className2: "cn240" },
    { className: "cn241", className2: "cn242" }
];
const NavigationLink_styles5 = [
    { className: "cn246", className2: "cn247" },
    { className: "cn248", className2: "cn249" },
    { className: "cn250", className2: "cn251" },
    { className: "cn252", className2: "cn253" }
];

export default function Page() {
  return (
    <>
      <StorefrontHeader className="cn1" data-cid="n1">
        <div className="cn2" data-cid="n2">
          <div className="cn3" data-cid="n3">
            <div className="cn4" data-cid="n4">
              <div className="cn5" data-cid="n5">
                <button className="cn6" data-cid="n6" data-component="button" aria-label="Menü öffnen">
                  <div className="cn7" data-cid="n7">
                    <span className="cn8" data-cid="n8" />
                    <span className="cn9" data-cid="n9" />
                    <span className="cn10" data-cid="n10" />
                  </div>
                </button>
              </div>
              <div className="cn11" data-cid="n11">
                <a className="cn12" data-cid="n12" data-component="link" href="/de/de">
                  <img className="cn13" data-cid="n13" data-component="image" alt="Spree" height="32" src="/assets/cloned/images/ccdab56ac016.png" width="90" />
                </a>
              </div>
              <div className="cn14" data-cid="n14">
                <div className="cn15" data-cid="n15">
                  <a className="cn16" data-cid="n16" data-component="link" href="https://demo.spreecommerce.org/de/de/wholesale">
                    Großhandel
                  </a>
                  <button className="cn17" data-cid="n17" data-component="button" aria-controls="radix-_R_579iujpfivb_" aria-expanded="false" aria-haspopup="dialog" aria-label="Region und Sprache" type="button">
                    <span className="cn18" data-cid="n18" aria-hidden="true">
                      <img className="cn19" data-cid="n19" data-component="image" alt="" height="18" src="/assets/cloned/svg/a9ea644efcfa.svg" width="18" />
                    </span>
                  </button>
                </div>
                <button className="cn20" data-cid="n20" data-component="button" aria-controls="search-overlay" aria-expanded="false" aria-label="Suche öffnen">
                  <svg className="cn21" data-cid="n21" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="m21 21-4.34-4.34" />
                    <circle cx="11" cy="11" r="8" />
                  </svg>
                </button>
                <div className="cn22" data-cid="n22">
                  <a className="cn23" data-cid="n23" data-component="link" aria-label="Konto" href="https://demo.spreecommerce.org/de/de/account">
                    <svg className="cn24" data-cid="n24" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                      <circle cx="12" cy="7" r="4" />
                    </svg>
                  </a>
                </div>
                <button className="cn25" data-cid="n25" data-component="button" aria-label="Warenkorb öffnen">
                  <svg className="cn26" data-cid="n26" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 10a4 4 0 0 1-8 0" />
                    <path d="M3.103 6.034h17.794" />
                    <path d="M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="cn27" data-cid="n27" id="search-overlay">
          <div className="cn28" data-cid="n28">
            <div className="cn29" data-cid="n29">
              <div className="cn30" data-cid="n30">
                <form className="cn31" data-cid="n31">
                  <div className="cn32" data-cid="n32" role="group">
                    <input className="cn33" data-cid="n33" data-component="select" aria-autocomplete="list" aria-controls="search-suggestions" aria-expanded="false" aria-label="Suche..." placeholder="Suche..." role="combobox" type="search" value="" />
                    <div className="cn34" data-cid="n34" role="group">
                      <svg className="cn35" data-cid="n35" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="m21 21-4.34-4.34" />
                        <circle cx="11" cy="11" r="8" />
                      </svg>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <button className="cn36" data-cid="n36" data-component="button" aria-label="Suche schließen">
              <svg className="cn37" data-cid="n37" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M18 6 6 18" />
                <path d="m6 6 12 12" />
              </svg>
            </button>
          </div>
        </div>
      </StorefrontHeader>
      <nav className="cn38" data-cid="n38" aria-label="Category navigation">
        <ul className="cn39" data-cid="n39">
          <li className="cn40" data-cid="n40">
            <a className="cn41" data-cid="n41" data-component="link" href="/de/de/c/kitchen">
              Küche
            </a>
            <ul className="cn42" data-cid="n42">
              {NavigationLink_data.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids[i]} styles={NavigationLink_styles[i]} />)}
            </ul>
          </li>
          {MegaMenuCategory_data.map((d, i) => <MegaMenuCategory key={i} d={d} cids={MegaMenuCategory_cids[i]} styles={MegaMenuCategory_styles[i]} />)}
          <li className="cn82" data-cid="n82">
            <a className="cn83" data-cid="n83" data-component="link" href="https://demo.spreecommerce.org/de/de/c/personal-care">
              Körperpflege
            </a>
            <ul className="cn84" data-cid="n84">
              {NavigationLink_data2.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids2[i]} styles={NavigationLink_styles2[i]} />)}
            </ul>
          </li>
        </ul>
      </nav>
      <main className="cn93" data-cid="n93">
        <div className="cn94" data-cid="n94">
          <section className="cn95" data-cid="n95">
            <div className="cn96" data-cid="n96">
              <div className="cn97" data-cid="n97">
                <h1 className="cn98" data-cid="n98" data-component="heading">
                  Spree Storefront
                </h1>
                <p className="cn99" data-cid="n99">
                  Eine produktionsreife, quelloffene Storefront mit Next.js, React und dem Spree TypeScript SDK. Selbst hosten. Eigener Stack. Kein Vendor Lock-in. Keine Plattformgebühren.
                </p>
                <div className="cn100" data-cid="n100">
                  <a className="cn101" data-cid="n101" data-component="button" href="/de/de/products">
                    Alle Produkte
                  </a>
                  <a className="cn102" data-cid="n102" data-component="button" href="https://github.com/spree/storefront" rel="noopener noreferrer" target="_blank">
                    Auf GitHub forken
                  </a>
                  <a className="cn103" data-cid="n103" data-component="button" href="https://spreecommerce.org/docs/developer/getting-started/quickstart" rel="noopener noreferrer" target="_blank">
                    Schnellstartanleitung→
                  </a>
                </div>
              </div>
            </div>
          </section>
          <section className="cn104" data-cid="n104">
            <div className="cn105" data-cid="n105">
              <h2 className="cn106" data-cid="n106" data-component="heading">
                Ausgewählte Produkte
              </h2>
              <a className="cn107" data-cid="n107" data-component="button" href="/de/de/products">
                Alle ansehen →
              </a>
            </div>
            <div className="cn108" data-cid="n108">
              <button className="cn109" data-cid="n109" aria-label="Vorherige Produkte" disabled type="button">
                <svg className="cn110" data-cid="n110" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="m15 18-6-6 6-6" />
                </svg>
              </button>
              <button className="cn111" data-cid="n111" data-component="button" aria-label="Nächste Produkte" type="button">
                <svg className="cn112" data-cid="n112" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="m9 18 6-6-6-6" />
                </svg>
              </button>
              <div className="cn113" data-cid="n113">
                <div className="cn114" data-cid="n114">
                  {ProductCard_data.map((d, i) => <ProductCard key={i} d={d} cids={ProductCard_cids[i]} styles={ProductCard_styles[i]} />)}
                </div>
              </div>
            </div>
          </section>
          <section className="cn187" data-cid="n187">
            <div className="cn188" data-cid="n188">
              <div className="cn189" data-cid="n189">
                <div className="cn190" data-cid="n190">
                  <span className="cn191" data-cid="n191">
                    {"Handel & Großhandel"}
                  </span>
                  <h2 className="cn192" data-cid="n192" data-component="heading">
                    Einkauf für Ihr Unternehmen?
                  </h2>
                  <p className="cn193" data-cid="n193">
                    Freigegebene Geschäftskunden erhalten Großhandelspreise auf den gesamten Katalog, schnelle Sammelbestellung per SKU und ihren eigenen Bestellverlauf. Einmal bewerben — wir prüfen und aktivieren Ihr Konto.
                  </p>
                  <div className="cn194" data-cid="n194">
                    <a className="cn195" data-cid="n195" data-component="button" href="https://demo.spreecommerce.org/de/de/wholesale">
                      Zum Großhandelsportal
                    </a>
                    <a className="cn196" data-cid="n196" data-component="button" href="https://demo.spreecommerce.org/de/de/wholesale/apply">
                      Konto beantragen
                    </a>
                  </div>
                </div>
                <ul className="cn197" data-cid="n197">
                  {CommerceBenefitCard_data.map((d, i) => <CommerceBenefitCard key={i} d={d} cids={CommerceBenefitCard_cids[i]} styles={CommerceBenefitCard_styles[i]} />)}
                </ul>
              </div>
            </div>
          </section>
        </div>
      </main>
      <StorefrontFooter className="cn207" data-cid="n207">
        <div className="cn208" data-cid="n208">
          <div className="cn209" data-cid="n209">
            <div className="cn210" data-cid="n210">
              <span className="cn211" data-cid="n211">
                Spree
              </span>
              <p className="cn212" data-cid="n212">
                Open-Source-E-Commerce basierend auf Spree REST API, TypeScript SDK und Next.js. Selbst hosten. Eigene Daten. Keine Plattformgebühren.
              </p>
              <div className="cn213" data-cid="n213">
                <a className="cn214" data-cid="n214" data-component="link" href="https://github.com/spree/storefront" rel="noopener noreferrer" target="_blank">
                  Diese Storefront auf GitHub forken→
                </a>
                <a className="cn215" data-cid="n215" data-component="link" href="https://spreecommerce.org/docs/developer/getting-started/quickstart" rel="noopener noreferrer" target="_blank">
                  Schnellstartanleitung
                </a>
                <a className="cn216" data-cid="n216" data-component="link" href="https://spreecommerce.org/" rel="noopener noreferrer" target="_blank">
                  Mehr über Spree Commerce erfahren
                </a>
              </div>
            </div>
            <div className="cn217" data-cid="n217">
              <h3 className="cn218" data-cid="n218" data-component="heading">
                Shop
              </h3>
              <ul className="cn219" data-cid="n219">
                {NavigationLink_data3.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids3[i]} styles={NavigationLink_styles3[i]} />)}
              </ul>
            </div>
            <div className="cn232" data-cid="n232">
              <h3 className="cn233" data-cid="n233" data-component="heading">
                Konto
              </h3>
              <ul className="cn234" data-cid="n234">
                {NavigationLink_data4.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids4[i]} styles={NavigationLink_styles4[i]} />)}
              </ul>
            </div>
            <div className="cn243" data-cid="n243">
              <h3 className="cn244" data-cid="n244" data-component="heading">
                Richtlinien
              </h3>
              <ul className="cn245" data-cid="n245">
                {NavigationLink_data5.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids5[i]} styles={NavigationLink_styles5[i]} />)}
              </ul>
            </div>
          </div>
          <div className="cn254" data-cid="n254">
            <p className="cn255" data-cid="n255">
              {"© 2026 Spree. Betrieben von "}
              <a className="cn256" data-cid="n256" data-component="link" href="https://spreecommerce.org/" target="_blank">
                Spree Commerce
              </a>
              {" & Next.js."}
            </p>
          </div>
        </div>
      </StorefrontFooter>
      <section className="cn257" data-cid="n257" aria-atomic="false" aria-label="Notifications alt+T" aria-live="polite" aria-relevant="additions text" />
    </>
  );
}
