import { StorefrontHeader, StorefrontFooter } from "../../../storefront/StorefrontChrome";
import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <>
      <div className="cn1" data-cid="n1" id="root">
        <div className="cn2" data-cid="n2" id="CustomProperties-P0-0">
          <div className="cn3" data-cid="n3">
            <div className="cn4" data-cid="n4">
              <div className="cn5" data-cid="n5">
                <div className="cn6" data-cid="n6">
                  <StorefrontHeader className="cn7" data-cid="n7">
                    <div className="cn8" data-cid="n8">
                      <h1 className="cn9" data-cid="n9" data-component="heading" role="presentation">
                        <a className="cn10" data-cid="n10" data-component="link" href="https://checkout.hydrogen.shop/de" target="_self">
                          Hydrogen Demo Store
                        </a>
                      </h1>
                    </div>
                  </StorefrontHeader>
                  <div className="cn11" data-cid="n11" id="main-wrapper">
                    <main className="cn12" data-cid="n12">
                      <div className="cn13" data-cid="n13">
                        <h1 className="cn14" data-cid="n14" data-component="heading">
                          <span className="cn15" data-cid="n15">
                            Anmelden
                          </span>
                        </h1>
                        <div className="cn16" data-cid="n16">
                          <div className="cn17" data-cid="n17">
                            <p className="cn18" data-cid="n18">
                              Anmelden oder ein Konto erstellen
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className="cn19" data-cid="n19">
                        <div className="cn20" data-cid="n20">
                          <div className="cn21" data-cid="n21" />
                          <div className="cn22" data-cid="n22" id="sign-in-options-extra">
                            <div className="cn23" data-cid="n23">
                              <div className="cn24" data-cid="n24">
                                <div className="cn25" data-cid="n25">
                                  <div className="cn26" data-cid="n26">
                                    <div className="cn27" data-cid="n27">
                                      <span className="cn28" data-cid="n28">
                                        oder
                                      </span>
                                      <span className="cn29" data-cid="n29" role="separator" />
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="cn30" data-cid="n30" id="email-form">
                        <div className="cn31" data-cid="n31">
                          <form className="cn32" data-cid="n32" id="FormP0-15">
                            <div className="cn33" data-cid="n33">
                              <div className="cn34" data-cid="n34">
                                <div className="cn35" data-cid="n35">
                                  <div className="cn36" data-cid="n36">
                                    <div className="cn37" data-cid="n37">
                                      <label className="cn38" data-cid="n38" htmlFor="customer-authentication-web-email" id="customer-authentication-web-email-label">
                                        <span className="cn39" data-cid="n39">
                                          <span className="cn40" data-cid="n40">
                                            E-Mail-Adresse
                                          </span>
                                        </span>
                                      </label>
                                      <input className="cn41" data-cid="n41" data-component="input" aria-labelledby="customer-authentication-web-email-label" aria-required="true" id="customer-authentication-web-email" placeholder="E-Mail-Adresse" type="email" value="" />
                                      <div className="cn42" data-cid="n42">
                                        <button className="cn43" data-cid="n43" data-component="button" aria-busy="false" aria-label="Weiter" aria-live="polite" type="submit">
                                          <span className="cn44" data-cid="n44">
                                            <span className="cn45" data-cid="n45">
                                              <span className="cn46" data-cid="n46" aria-hidden="true">
                                                <svg className="cn47" data-cid="n47" data-component="icon" aria-hidden="true" viewBox="0 0 14 14" focusable="false" fill="currentColor">
                                                  <use href="#arrowRight" />
                                                </svg>
                                              </span>
                                            </span>
                                          </span>
                                        </button>
                                      </div>
                                    </div>
                                  </div>
                                  <div className="cn48" data-cid="n48">
                                    <div className="cn49" data-cid="n49">
                                      <div className="cn50" data-cid="n50">
                                        <input className="cn51" data-cid="n51" data-component="input" id="marketing-consent" name="marketing-consent" type="checkbox" value="" />
                                        <div className="cn52" data-cid="n52">
                                          <span className="cn53" data-cid="n53">
                                            <span className="cn54" data-cid="n54" aria-hidden="true">
                                              <svg className="cn55" data-cid="n55" data-component="icon" aria-hidden="true" viewBox="0 0 14 14" focusable="false" fill="currentColor">
                                                <use href="#check" />
                                              </svg>
                                            </span>
                                          </span>
                                        </div>
                                      </div>
                                      <label className="cn56" data-cid="n56" htmlFor="marketing-consent">
                                        Neuigkeiten und Angebote via E-Mail erhalten
                                      </label>
                                    </div>
                                  </div>
                                </div>
                                <p className="cn57" data-cid="n57">
                                  {"Wenn du fortfährst, stimmst du unseren "}
                                  <button className="cn58" data-cid="n58" data-component="button" aria-haspopup="dialog" type="button">
                                    <span className="cn59" data-cid="n59">
                                      AGB
                                    </span>
                                  </button>
                                  {" zu."}
                                </p>
                              </div>
                            </div>
                            <div className="cn60" data-cid="n60">
                              <button className="cn61" data-cid="n61" data-component="button" aria-hidden="true" type="submit">
                                Senden
                              </button>
                            </div>
                          </form>
                        </div>
                      </div>
                    </main>
                  </div>
                  <StorefrontFooter className="cn62" data-cid="n62">
                    <div className="cn63" data-cid="n63">
                      <button className="cn64" data-cid="n64" data-component="button" aria-haspopup="dialog" type="button">
                        <span className="cn65" data-cid="n65">
                          Datenschutzerklärung
                        </span>
                      </button>
                    </div>
                  </StorefrontFooter>
                </div>
              </div>
            </div>
            <div className="cn66" data-cid="n66" id="PortalHost" />
          </div>
        </div>
        <div className="cn67" data-cid="n67" aria-hidden="true" id="forwarding-external-new-window-message">
          externalNewWindow
        </div>
        <div className="cn68" data-cid="n68" aria-hidden="true" id="forwarding-new-window-message">
          newWindow
        </div>
        <div className="cn69" data-cid="n69" aria-hidden="true" id="forwarding-external-message">
          external
        </div>
      </div>
      {" "}
    </>
  );
}
