import { StorefrontHeader, StorefrontFooter } from "../../../../storefront/StorefrontChrome";
import "./ditto.css";
import NavigationLink from "./components/navigation-link";
import MegaMenuCategory from "./components/mega-menu-category";
import CategoryLink from "./components/category-link";
import FilterMenuTrigger from "./components/filter-menu-trigger";
import ProductCard from "./components/product-card";
// Generated by clone-site. Do not edit by hand.
const NavigationLink_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kaffeemaschinen", label: "Kaffeemaschinen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/heissluftfritteusen", label: "Heißluftfritteusen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/mixer", label: "Mixer" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/wasserkocher", label: "Wasserkocher" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/toaster", label: "Toaster" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kuchenmaschinen", label: "Küchenmaschinen" }
];
const MegaMenuCategory_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/air-and-climate", label: "Luft & Klima", href2: "https://demo.spreecommerce.org/de/de/c/air-and-climate/luftreiniger", label2: "Luftreiniger", href3: "https://demo.spreecommerce.org/de/de/c/air-and-climate/luftbefeuchter", label3: "Luftbefeuchter", href4: "https://demo.spreecommerce.org/de/de/c/air-and-climate/ventilator", label4: "Ventilator" },
    { href: "https://demo.spreecommerce.org/de/de/c/garment-care", label: "Kleidungspflege", href2: "https://demo.spreecommerce.org/de/de/c/garment-care/dampferzeuger", label2: "Dampferzeuger", href3: "https://demo.spreecommerce.org/de/de/c/garment-care/handdampfreiniger", label3: "Handdampfreiniger", href4: "https://demo.spreecommerce.org/de/de/c/garment-care/bugeleisen", label4: "Bügeleisen" },
    { href: "https://demo.spreecommerce.org/de/de/c/floor-care", label: "Bodenpflege", href2: "https://demo.spreecommerce.org/de/de/c/floor-care/akku-staubsauger", label2: "Akku-Staubsauger", href3: "https://demo.spreecommerce.org/de/de/c/floor-care/saugroboter", label3: "Saugroboter", href4: "https://demo.spreecommerce.org/de/de/c/floor-care/aufrechte-staubsauger", label4: "Aufrechte Staubsauger" }
];
const NavigationLink_data2 = [
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haartrockner", label: "Haartrockner" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haarglatter", label: "Haarglätter" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haartrimmer", label: "Haartrimmer" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/elektrorasierer", label: "Elektrorasierer" }
];
const CategoryLink_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kaffeemaschinen", label: "Kaffeemaschinen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/heissluftfritteusen", label: "Heißluftfritteusen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/mixer", label: "Mixer" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/wasserkocher", label: "Wasserkocher" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/toaster", label: "Toaster" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kuchenmaschinen", label: "Küchenmaschinen" }
];
const FilterMenuTrigger_data = [
    { id: "radix-_r_q_", label: "Farbe" },
    { id: "radix-_r_s_", label: "Preis" },
    { id: "radix-_r_u_", label: "Verfügbarkeit" }
];
const ProductCard_data = [
    { alt: "Digitale Heißluftfritteuse 6.2L", imgSrc: "/assets/cloned/images/4467de6bff7e.jpg", href: "/de/de/products/digitale-heissluftfritteuse-6-2l", title: "Digitale Heißluftfritteuse 6.2L", text: "€169,99" },
    { alt: "Kaffeevollautomat", imgSrc: "/assets/cloned/images/48512731246e.jpg", href: "https://demo.spreecommerce.org/de/de/products/kaffeevollautomat?category_id=ctg_Ej9hxLZ9ck", title: "Kaffeevollautomat", text: "€819,99" },
    { alt: "Siebträger-Espressomaschine", imgSrc: "/assets/cloned/images/1c316bd76717.jpg", href: "https://demo.spreecommerce.org/de/de/products/siebtrager-espressomaschine?category_id=ctg_Ej9hxLZ9ck", title: "Siebträger-Espressomaschine", text: "€509,99" },
    { alt: "Filterkaffeemaschine 1.5L", imgSrc: "/assets/cloned/images/b41b1840fe0b.jpg", href: "https://demo.spreecommerce.org/de/de/products/filterkaffeemaschine-1-5l?category_id=ctg_Ej9hxLZ9ck", title: "Filterkaffeemaschine 1.5L", text: "€84,99" },
    { alt: "Digitale Heißluftfritteuse 4.2L", imgSrc: "/assets/cloned/images/e5ca3e70300a.jpg", href: "https://demo.spreecommerce.org/de/de/products/digitale-heissluftfritteuse-4-2l?category_id=ctg_Ej9hxLZ9ck", title: "Digitale Heißluftfritteuse 4.2L", text: "€109,99" },
    { alt: "Doppelkorb-Heißluftfritteuse 8L", imgSrc: "/assets/cloned/images/3284c4466783.jpg", href: "https://demo.spreecommerce.org/de/de/products/doppelkorb-heissluftfritteuse-8l?category_id=ctg_Ej9hxLZ9ck", title: "Doppelkorb-Heißluftfritteuse 8L", text: "€229,99" },
    { alt: "Einzelportionsmixer 600ml", imgSrc: "/assets/cloned/images/49f5444df677.jpg", href: "https://demo.spreecommerce.org/de/de/products/einzelportionsmixer-600ml?category_id=ctg_Ej9hxLZ9ck", title: "Einzelportionsmixer 600ml", text: "€46,99" },
    { alt: "Hochleistungsmixer 2.0L", imgSrc: "/assets/cloned/images/5efa1f20c1c2.jpg", href: "https://demo.spreecommerce.org/de/de/products/hochleistungsmixer-2-0l?category_id=ctg_Ej9hxLZ9ck", title: "Hochleistungsmixer 2.0L", text: "€189,99" },
    { alt: "Elektrischer Wasserkocher 1.7L", imgSrc: "/assets/cloned/images/291094e50f28.jpg", href: "https://demo.spreecommerce.org/de/de/products/elektrischer-wasserkocher-1-7l?category_id=ctg_Ej9hxLZ9ck", title: "Elektrischer Wasserkocher 1.7L", text: "€41,99" },
    { alt: "Wasserkocher mit Temperaturwahl 1.7L", imgSrc: "/assets/cloned/images/2387858a2a11.jpg", href: "https://demo.spreecommerce.org/de/de/products/wasserkocher-mit-temperaturwahl-1-7l?category_id=ctg_Ej9hxLZ9ck", title: "Wasserkocher mit Temperaturwahl 1.7L", text: "€74,99" },
    { alt: "2-Scheiben-Toaster", imgSrc: "/assets/cloned/images/63f02400c5c7.jpg", href: "https://demo.spreecommerce.org/de/de/products/2-scheiben-toaster?category_id=ctg_Ej9hxLZ9ck", title: "2-Scheiben-Toaster", text: "€37,99" },
    { alt: "4-Scheiben-Toaster", imgSrc: "/assets/cloned/images/32baa566959f.jpg", href: "https://demo.spreecommerce.org/de/de/products/4-scheiben-toaster?category_id=ctg_Ej9hxLZ9ck", title: "4-Scheiben-Toaster", text: "€59,99" },
    { alt: "Küchenmaschine 3.0L", imgSrc: "/assets/cloned/images/c62802537119.jpg", href: "https://demo.spreecommerce.org/de/de/products/kuchenmaschine-3-0l?category_id=ctg_Ej9hxLZ9ck", title: "Küchenmaschine 3.0L", text: "€139,99" }
];
const NavigationLink_data3 = [
    { href: "/de/de/products", label: "Alle Produkte" },
    { href: "/de/de/c/kitchen", label: "Küche" },
    { href: "https://demo.spreecommerce.org/de/de/c/air-and-climate", label: "Luft & Klima" },
    { href: "https://demo.spreecommerce.org/de/de/c/garment-care", label: "Kleidungspflege" },
    { href: "https://demo.spreecommerce.org/de/de/c/floor-care", label: "Bodenpflege" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care", label: "Körperpflege" }
];
const NavigationLink_data4 = [
    { href: "https://demo.spreecommerce.org/de/de/account", label: "Mein Konto" },
    { href: "https://demo.spreecommerce.org/de/de/account/orders", label: "Bestellverlauf" },
    { href: "/de/de/cart", label: "Warenkorb" },
    { href: "https://demo.spreecommerce.org/de/de/wholesale", label: "Handel & Großhandel" }
];
const NavigationLink_data5 = [
    { href: "https://demo.spreecommerce.org/de/de/policies/shipping-policy", label: "Versandrichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/privacy-policy", label: "Datenschutzrichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/returns-policy", label: "Rückgaberichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/terms-of-service", label: "Nutzungsbedingungen" }
];
const NavigationLink_cids: string[][] = [
    ["n43", "n44"],
    ["n45", "n46"],
    ["n47", "n48"],
    ["n49", "n50"],
    ["n51", "n52"],
    ["n53", "n54"]
];
const MegaMenuCategory_cids: string[][] = [
    ["n55", "n56", "n57", "n58", "n59", "n60", "n61", "n62", "n63"],
    ["n64", "n65", "n66", "n67", "n68", "n69", "n70", "n71", "n72"],
    ["n73", "n74", "n75", "n76", "n77", "n78", "n79", "n80", "n81"]
];
const NavigationLink_cids2: string[][] = [
    ["n85", "n86"],
    ["n87", "n88"],
    ["n89", "n90"],
    ["n91", "n92"]
];
const CategoryLink_cids: string[][] = [
    ["n108"],
    ["n109"],
    ["n110"],
    ["n111"],
    ["n112"],
    ["n113"]
];
const FilterMenuTrigger_cids: string[][] = [
    ["n119", "n120", "n121"],
    ["n122", "n123", "n124"],
    ["n125", "n126", "n127"]
];
const ProductCard_cids: string[][] = [
    ["n142", "n143", "n144", "n145", "n146", "n147", "n148", "n149"],
    ["n150", "n151", "n152", "n153", "n154", "n155", "n156", "n157"],
    ["n158", "n159", "n160", "n161", "n162", "n163", "n164", "n165"],
    ["n166", "n167", "n168", "n169", "n170", "n171", "n172", "n173"],
    ["n174", "n175", "n176", "n177", "n178", "n179", "n180", "n181"],
    ["n182", "n183", "n184", "n185", "n186", "n187", "n188", "n189"],
    ["n190", "n191", "n192", "n193", "n194", "n195", "n196", "n197"],
    ["n198", "n199", "n200", "n201", "n202", "n203", "n204", "n205"],
    ["n206", "n207", "n208", "n209", "n210", "n211", "n212", "n213"],
    ["n214", "n215", "n216", "n217", "n218", "n219", "n220", "n221"],
    ["n222", "n223", "n224", "n225", "n226", "n227", "n228", "n229"],
    ["n230", "n231", "n232", "n233", "n234", "n235", "n236", "n237"],
    ["n238", "n239", "n240", "n241", "n242", "n243", "n244", "n245"]
];
const NavigationLink_cids3: string[][] = [
    ["n261", "n262"],
    ["n263", "n264"],
    ["n265", "n266"],
    ["n267", "n268"],
    ["n269", "n270"],
    ["n271", "n272"]
];
const NavigationLink_cids4: string[][] = [
    ["n276", "n277"],
    ["n278", "n279"],
    ["n280", "n281"],
    ["n282", "n283"]
];
const NavigationLink_cids5: string[][] = [
    ["n287", "n288"],
    ["n289", "n290"],
    ["n291", "n292"],
    ["n293", "n294"]
];
const NavigationLink_styles = [
    { className: "cn43", className2: "cn44" },
    { className: "cn45", className2: "cn46" },
    { className: "cn47", className2: "cn48" },
    { className: "cn49", className2: "cn50" },
    { className: "cn51", className2: "cn52" },
    { className: "cn53", className2: "cn54" }
];
const MegaMenuCategory_styles = [
    { className: "cn55", className2: "cn56", className3: "cn57", className4: "cn58", className5: "cn59", className6: "cn60", className7: "cn61", className8: "cn62", className9: "cn63" },
    { className: "cn64", className2: "cn65", className3: "cn66", className4: "cn67", className5: "cn68", className6: "cn69", className7: "cn70", className8: "cn71", className9: "cn72" },
    { className: "cn73", className2: "cn74", className3: "cn75", className4: "cn76", className5: "cn77", className6: "cn78", className7: "cn79", className8: "cn80", className9: "cn81" }
];
const NavigationLink_styles2 = [
    { className: "cn85", className2: "cn86" },
    { className: "cn87", className2: "cn88" },
    { className: "cn89", className2: "cn90" },
    { className: "cn91", className2: "cn92" }
];
const CategoryLink_styles = [
    { className: "cn108" },
    { className: "cn109" },
    { className: "cn110" },
    { className: "cn111" },
    { className: "cn112" },
    { className: "cn113" }
];
const FilterMenuTrigger_styles = [
    { className: "cn119", className2: "cn120", className3: "cn121" },
    { className: "cn122", className2: "cn123", className3: "cn124" },
    { className: "cn125", className2: "cn126", className3: "cn127" }
];
const ProductCard_styles = [
    { className: "cn142", className2: "cn143", className3: "cn144", className4: "cn145", className5: "cn146", className6: "cn147", className7: "cn148", className8: "cn149" },
    { className: "cn150", className2: "cn151", className3: "cn152", className4: "cn153", className5: "cn154", className6: "cn155", className7: "cn156", className8: "cn157" },
    { className: "cn158", className2: "cn159", className3: "cn160", className4: "cn161", className5: "cn162", className6: "cn163", className7: "cn164", className8: "cn165" },
    { className: "cn166", className2: "cn167", className3: "cn168", className4: "cn169", className5: "cn170", className6: "cn171", className7: "cn172", className8: "cn173" },
    { className: "cn174", className2: "cn175", className3: "cn176", className4: "cn177", className5: "cn178", className6: "cn179", className7: "cn180", className8: "cn181" },
    { className: "cn182", className2: "cn183", className3: "cn184", className4: "cn185", className5: "cn186", className6: "cn187", className7: "cn188", className8: "cn189" },
    { className: "cn190", className2: "cn191", className3: "cn192", className4: "cn193", className5: "cn194", className6: "cn195", className7: "cn196", className8: "cn197" },
    { className: "cn198", className2: "cn199", className3: "cn200", className4: "cn201", className5: "cn202", className6: "cn203", className7: "cn204", className8: "cn205" },
    { className: "cn206", className2: "cn207", className3: "cn208", className4: "cn209", className5: "cn210", className6: "cn211", className7: "cn212", className8: "cn213" },
    { className: "cn214", className2: "cn215", className3: "cn216", className4: "cn217", className5: "cn218", className6: "cn219", className7: "cn220", className8: "cn221" },
    { className: "cn222", className2: "cn223", className3: "cn224", className4: "cn225", className5: "cn226", className6: "cn227", className7: "cn228", className8: "cn229" },
    { className: "cn230", className2: "cn231", className3: "cn232", className4: "cn233", className5: "cn234", className6: "cn235", className7: "cn236", className8: "cn237" },
    { className: "cn238", className2: "cn239", className3: "cn240", className4: "cn241", className5: "cn242", className6: "cn243", className7: "cn244", className8: "cn245" }
];
const NavigationLink_styles3 = [
    { className: "cn261", className2: "cn262" },
    { className: "cn263", className2: "cn264" },
    { className: "cn265", className2: "cn266" },
    { className: "cn267", className2: "cn268" },
    { className: "cn269", className2: "cn270" },
    { className: "cn271", className2: "cn272" }
];
const NavigationLink_styles4 = [
    { className: "cn276", className2: "cn277" },
    { className: "cn278", className2: "cn279" },
    { className: "cn280", className2: "cn281" },
    { className: "cn282", className2: "cn283" }
];
const NavigationLink_styles5 = [
    { className: "cn287", className2: "cn288" },
    { className: "cn289", className2: "cn290" },
    { className: "cn291", className2: "cn292" },
    { className: "cn293", className2: "cn294" }
];

export default function Page() {
  return (
    <>
      <StorefrontHeader className="cn1" data-cid="n1">
        <div className="cn2" data-cid="n2">
          <div className="cn3" data-cid="n3">
            <div className="cn4" data-cid="n4">
              <div className="cn5" data-cid="n5">
                <button className="cn6" data-cid="n6" data-component="button" aria-label="Menü öffnen">
                  <div className="cn7" data-cid="n7">
                    <span className="cn8" data-cid="n8" />
                    <span className="cn9" data-cid="n9" />
                    <span className="cn10" data-cid="n10" />
                  </div>
                </button>
              </div>
              <div className="cn11" data-cid="n11">
                <a className="cn12" data-cid="n12" data-component="link" href="/de/de">
                  <img className="cn13" data-cid="n13" data-component="image" alt="Spree" height="32" src="/assets/cloned/images/ccdab56ac016.png" width="90" />
                </a>
              </div>
              <div className="cn14" data-cid="n14">
                <div className="cn15" data-cid="n15">
                  <a className="cn16" data-cid="n16" data-component="link" href="https://demo.spreecommerce.org/de/de/wholesale">
                    Großhandel
                  </a>
                  <button className="cn17" data-cid="n17" data-component="button" aria-controls="radix-_R_579iujpfivb_" aria-expanded="false" aria-haspopup="dialog" aria-label="Region und Sprache" type="button">
                    <span className="cn18" data-cid="n18" aria-hidden="true">
                      <img className="cn19" data-cid="n19" data-component="image" alt="" height="18" src="/assets/cloned/svg/0c335f5d5ff2.svg" width="18" />
                    </span>
                  </button>
                </div>
                <button className="cn20" data-cid="n20" data-component="button" aria-controls="search-overlay" aria-expanded="false" aria-label="Suche öffnen">
                  <svg className="cn21" data-cid="n21" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="m21 21-4.34-4.34" />
                    <circle cx="11" cy="11" r="8" />
                  </svg>
                </button>
                <div className="cn22" data-cid="n22">
                  <a className="cn23" data-cid="n23" data-component="link" aria-label="Konto" href="https://demo.spreecommerce.org/de/de/account">
                    <svg className="cn24" data-cid="n24" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                      <circle cx="12" cy="7" r="4" />
                    </svg>
                  </a>
                </div>
                <button className="cn25" data-cid="n25" data-component="button" aria-label="Warenkorb öffnen">
                  <svg className="cn26" data-cid="n26" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 10a4 4 0 0 1-8 0" />
                    <path d="M3.103 6.034h17.794" />
                    <path d="M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="cn27" data-cid="n27" id="search-overlay">
          <div className="cn28" data-cid="n28">
            <div className="cn29" data-cid="n29">
              <div className="cn30" data-cid="n30">
                <form className="cn31" data-cid="n31">
                  <div className="cn32" data-cid="n32" role="group">
                    <input className="cn33" data-cid="n33" data-component="select" aria-autocomplete="list" aria-controls="search-suggestions" aria-expanded="false" aria-label="Suche..." placeholder="Suche..." role="combobox" type="search" value="" />
                    <div className="cn34" data-cid="n34" role="group">
                      <svg className="cn35" data-cid="n35" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="m21 21-4.34-4.34" />
                        <circle cx="11" cy="11" r="8" />
                      </svg>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <button className="cn36" data-cid="n36" data-component="button" aria-label="Suche schließen">
              <svg className="cn37" data-cid="n37" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M18 6 6 18" />
                <path d="m6 6 12 12" />
              </svg>
            </button>
          </div>
        </div>
      </StorefrontHeader>
      <nav className="cn38" data-cid="n38" aria-label="Category navigation">
        <ul className="cn39" data-cid="n39">
          <li className="cn40" data-cid="n40">
            <a className="cn41" data-cid="n41" data-component="link" href="/de/de/c/kitchen">
              Küche
            </a>
            <ul className="cn42" data-cid="n42">
              {NavigationLink_data.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids[i]} styles={NavigationLink_styles[i]} />)}
            </ul>
          </li>
          {MegaMenuCategory_data.map((d, i) => <MegaMenuCategory key={i} d={d} cids={MegaMenuCategory_cids[i]} styles={MegaMenuCategory_styles[i]} />)}
          <li className="cn82" data-cid="n82">
            <a className="cn83" data-cid="n83" data-component="link" href="https://demo.spreecommerce.org/de/de/c/personal-care">
              Körperpflege
            </a>
            <ul className="cn84" data-cid="n84">
              {NavigationLink_data2.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids2[i]} styles={NavigationLink_styles2[i]} />)}
            </ul>
          </li>
        </ul>
      </nav>
      <main className="cn93" data-cid="n93">
        <div className="cn94" data-cid="n94">
          <div className="cn95" data-cid="n95">
            <div className="cn96" data-cid="n96">
              <nav className="cn97" data-cid="n97" data-component="nav" aria-label="Brotkrümelnavigation">
                <ol className="cn98" data-cid="n98">
                  <li className="cn99" data-cid="n99">
                    <a className="cn100" data-cid="n100" data-component="link" href="/de/de">
                      Startseite
                    </a>
                  </li>
                  <li className="cn101" data-cid="n101">
                    <svg className="cn102" data-cid="n102" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="m9 18 6-6-6-6" />
                    </svg>
                    <span className="cn103" data-cid="n103" aria-current="page">
                      Küche
                    </span>
                  </li>
                </ol>
              </nav>
              <div className="cn104" data-cid="n104">
                <h1 className="cn105" data-cid="n105" data-component="heading">
                  Küche
                </h1>
              </div>
            </div>
          </div>
          <div className="cn106" data-cid="n106">
            <div className="cn107" data-cid="n107">
              {CategoryLink_data.map((d, i) => <CategoryLink key={i} d={d} cids={CategoryLink_cids[i]} styles={CategoryLink_styles[i]} />)}
            </div>
          </div>
          <div className="cn114" data-cid="n114">
            <div className="cn115" data-cid="n115" aria-busy="false">
              <div className="cn116" data-cid="n116">
                <div className="cn117" data-cid="n117">
                  <div className="cn118" data-cid="n118">
                    {FilterMenuTrigger_data.map((d, i) => <FilterMenuTrigger key={i} d={d} cids={FilterMenuTrigger_cids[i]} styles={FilterMenuTrigger_styles[i]} />)}
                  </div>
                  <div className="cn128" data-cid="n128">
                    <span className="cn129" data-cid="n129">
                      13 Produkte
                    </span>
                    <button className="cn130" data-cid="n130" data-component="button" aria-expanded="false" aria-haspopup="menu" id="radix-_r_10_" type="button">
                      <span className="cn131" data-cid="n131">
                        Sortieren
                      </span>
                      <svg className="cn132" data-cid="n132" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="m6 9 6 6 6-6" />
                      </svg>
                    </button>
                  </div>
                </div>
                <div className="cn133" data-cid="n133">
                  <button className="cn134" data-cid="n134" type="button">
                    <svg className="cn135" data-cid="n135" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M10 5H3" />
                      <path d="M12 19H3" />
                      <path d="M14 3v4" />
                      <path d="M16 17v4" />
                      <path d="M21 12h-9" />
                      <path d="M21 19h-5" />
                      <path d="M21 5h-7" />
                      <path d="M8 10v4" />
                      <path d="M8 12H3" />
                    </svg>
                    <span className="cn136" data-cid="n136">
                      Filter
                    </span>
                  </button>
                  <div className="cn137" data-cid="n137">
                    <button className="cn138" data-cid="n138" aria-expanded="false" aria-haspopup="menu" id="radix-_r_12_" type="button">
                      <span className="cn139" data-cid="n139">
                        Sortieren
                      </span>
                      <svg className="cn140" data-cid="n140" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="m6 9 6 6 6-6" />
                      </svg>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div className="cn141" data-cid="n141">
              {ProductCard_data.map((d, i) => <ProductCard key={i} d={d} cids={ProductCard_cids[i]} styles={ProductCard_styles[i]} />)}
            </div>
            <div className="cn246" data-cid="n246">
              <p className="cn247" data-cid="n247">
                Keine weiteren Produkte zum Laden
              </p>
            </div>
          </div>
        </div>
      </main>
      <StorefrontFooter className="cn248" data-cid="n248">
        <div className="cn249" data-cid="n249">
          <div className="cn250" data-cid="n250">
            <div className="cn251" data-cid="n251">
              <span className="cn252" data-cid="n252">
                Spree
              </span>
              <p className="cn253" data-cid="n253">
                Open-Source-E-Commerce basierend auf Spree REST API, TypeScript SDK und Next.js. Selbst hosten. Eigene Daten. Keine Plattformgebühren.
              </p>
              <div className="cn254" data-cid="n254">
                <a className="cn255" data-cid="n255" data-component="link" href="https://github.com/spree/storefront" rel="noopener noreferrer" target="_blank">
                  Diese Storefront auf GitHub forken→
                </a>
                <a className="cn256" data-cid="n256" data-component="link" href="https://spreecommerce.org/docs/developer/getting-started/quickstart" rel="noopener noreferrer" target="_blank">
                  Schnellstartanleitung
                </a>
                <a className="cn257" data-cid="n257" data-component="link" href="https://spreecommerce.org/" rel="noopener noreferrer" target="_blank">
                  Mehr über Spree Commerce erfahren
                </a>
              </div>
            </div>
            <div className="cn258" data-cid="n258">
              <h3 className="cn259" data-cid="n259" data-component="heading">
                Shop
              </h3>
              <ul className="cn260" data-cid="n260">
                {NavigationLink_data3.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids3[i]} styles={NavigationLink_styles3[i]} />)}
              </ul>
            </div>
            <div className="cn273" data-cid="n273">
              <h3 className="cn274" data-cid="n274" data-component="heading">
                Konto
              </h3>
              <ul className="cn275" data-cid="n275">
                {NavigationLink_data4.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids4[i]} styles={NavigationLink_styles4[i]} />)}
              </ul>
            </div>
            <div className="cn284" data-cid="n284">
              <h3 className="cn285" data-cid="n285" data-component="heading">
                Richtlinien
              </h3>
              <ul className="cn286" data-cid="n286">
                {NavigationLink_data5.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids5[i]} styles={NavigationLink_styles5[i]} />)}
              </ul>
            </div>
          </div>
          <div className="cn295" data-cid="n295">
            <p className="cn296" data-cid="n296">
              {"© 2026 Spree. Betrieben von "}
              <a className="cn297" data-cid="n297" data-component="link" href="https://spreecommerce.org/" target="_blank">
                Spree Commerce
              </a>
              {" & Next.js."}
            </p>
          </div>
        </div>
      </StorefrontFooter>
      <section className="cn298" data-cid="n298" aria-atomic="false" aria-label="Notifications alt+T" aria-live="polite" aria-relevant="additions text" />
    </>
  );
}
