import { StorefrontHeader, StorefrontFooter } from "../../../storefront/StorefrontChrome";
import "./ditto.css";
import NavigationLink from "./components/navigation-link";
import MegaMenuCategory from "./components/mega-menu-category";
// Generated by clone-site. Do not edit by hand.
const NavigationLink_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kaffeemaschinen", label: "Kaffeemaschinen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/heissluftfritteusen", label: "Heißluftfritteusen" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/mixer", label: "Mixer" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/wasserkocher", label: "Wasserkocher" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/toaster", label: "Toaster" },
    { href: "https://demo.spreecommerce.org/de/de/c/kitchen/kuchenmaschinen", label: "Küchenmaschinen" }
];
const MegaMenuCategory_data = [
    { href: "https://demo.spreecommerce.org/de/de/c/air-and-climate", label: "Luft & Klima", href2: "https://demo.spreecommerce.org/de/de/c/air-and-climate/luftreiniger", label2: "Luftreiniger", href3: "https://demo.spreecommerce.org/de/de/c/air-and-climate/luftbefeuchter", label3: "Luftbefeuchter", href4: "https://demo.spreecommerce.org/de/de/c/air-and-climate/ventilator", label4: "Ventilator" },
    { href: "https://demo.spreecommerce.org/de/de/c/garment-care", label: "Kleidungspflege", href2: "https://demo.spreecommerce.org/de/de/c/garment-care/dampferzeuger", label2: "Dampferzeuger", href3: "https://demo.spreecommerce.org/de/de/c/garment-care/handdampfreiniger", label3: "Handdampfreiniger", href4: "https://demo.spreecommerce.org/de/de/c/garment-care/bugeleisen", label4: "Bügeleisen" },
    { href: "https://demo.spreecommerce.org/de/de/c/floor-care", label: "Bodenpflege", href2: "https://demo.spreecommerce.org/de/de/c/floor-care/akku-staubsauger", label2: "Akku-Staubsauger", href3: "https://demo.spreecommerce.org/de/de/c/floor-care/saugroboter", label3: "Saugroboter", href4: "https://demo.spreecommerce.org/de/de/c/floor-care/aufrechte-staubsauger", label4: "Aufrechte Staubsauger" }
];
const NavigationLink_data2 = [
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haartrockner", label: "Haartrockner" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haarglatter", label: "Haarglätter" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/haartrimmer", label: "Haartrimmer" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care/elektrorasierer", label: "Elektrorasierer" }
];
const NavigationLink_data3 = [
    { href: "/de/de/products", label: "Alle Produkte" },
    { href: "/de/de/c/kitchen", label: "Küche" },
    { href: "https://demo.spreecommerce.org/de/de/c/air-and-climate", label: "Luft & Klima" },
    { href: "https://demo.spreecommerce.org/de/de/c/garment-care", label: "Kleidungspflege" },
    { href: "https://demo.spreecommerce.org/de/de/c/floor-care", label: "Bodenpflege" },
    { href: "https://demo.spreecommerce.org/de/de/c/personal-care", label: "Körperpflege" }
];
const NavigationLink_data4 = [
    { href: "https://demo.spreecommerce.org/de/de/account", label: "Mein Konto" },
    { href: "https://demo.spreecommerce.org/de/de/account/orders", label: "Bestellverlauf" },
    { href: "/de/de/cart", label: "Warenkorb" },
    { href: "https://demo.spreecommerce.org/de/de/wholesale", label: "Handel & Großhandel" }
];
const NavigationLink_data5 = [
    { href: "https://demo.spreecommerce.org/de/de/policies/shipping-policy", label: "Versandrichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/privacy-policy", label: "Datenschutzrichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/returns-policy", label: "Rückgaberichtlinie" },
    { href: "https://demo.spreecommerce.org/de/de/policies/terms-of-service", label: "Nutzungsbedingungen" }
];
const NavigationLink_cids: string[][] = [
    ["n43", "n44"],
    ["n45", "n46"],
    ["n47", "n48"],
    ["n49", "n50"],
    ["n51", "n52"],
    ["n53", "n54"]
];
const MegaMenuCategory_cids: string[][] = [
    ["n55", "n56", "n57", "n58", "n59", "n60", "n61", "n62", "n63"],
    ["n64", "n65", "n66", "n67", "n68", "n69", "n70", "n71", "n72"],
    ["n73", "n74", "n75", "n76", "n77", "n78", "n79", "n80", "n81"]
];
const NavigationLink_cids2: string[][] = [
    ["n85", "n86"],
    ["n87", "n88"],
    ["n89", "n90"],
    ["n91", "n92"]
];
const NavigationLink_cids3: string[][] = [
    ["n114", "n115"],
    ["n116", "n117"],
    ["n118", "n119"],
    ["n120", "n121"],
    ["n122", "n123"],
    ["n124", "n125"]
];
const NavigationLink_cids4: string[][] = [
    ["n129", "n130"],
    ["n131", "n132"],
    ["n133", "n134"],
    ["n135", "n136"]
];
const NavigationLink_cids5: string[][] = [
    ["n140", "n141"],
    ["n142", "n143"],
    ["n144", "n145"],
    ["n146", "n147"]
];
const NavigationLink_styles = [
    { className: "cn43", className2: "cn44" },
    { className: "cn45", className2: "cn46" },
    { className: "cn47", className2: "cn48" },
    { className: "cn49", className2: "cn50" },
    { className: "cn51", className2: "cn52" },
    { className: "cn53", className2: "cn54" }
];
const MegaMenuCategory_styles = [
    { className: "cn55", className2: "cn56", className3: "cn57", className4: "cn58", className5: "cn59", className6: "cn60", className7: "cn61", className8: "cn62", className9: "cn63" },
    { className: "cn64", className2: "cn65", className3: "cn66", className4: "cn67", className5: "cn68", className6: "cn69", className7: "cn70", className8: "cn71", className9: "cn72" },
    { className: "cn73", className2: "cn74", className3: "cn75", className4: "cn76", className5: "cn77", className6: "cn78", className7: "cn79", className8: "cn80", className9: "cn81" }
];
const NavigationLink_styles2 = [
    { className: "cn85", className2: "cn86" },
    { className: "cn87", className2: "cn88" },
    { className: "cn89", className2: "cn90" },
    { className: "cn91", className2: "cn92" }
];
const NavigationLink_styles3 = [
    { className: "cn114", className2: "cn115" },
    { className: "cn116", className2: "cn117" },
    { className: "cn118", className2: "cn119" },
    { className: "cn120", className2: "cn121" },
    { className: "cn122", className2: "cn123" },
    { className: "cn124", className2: "cn125" }
];
const NavigationLink_styles4 = [
    { className: "cn129", className2: "cn130" },
    { className: "cn131", className2: "cn132" },
    { className: "cn133", className2: "cn134" },
    { className: "cn135", className2: "cn136" }
];
const NavigationLink_styles5 = [
    { className: "cn140", className2: "cn141" },
    { className: "cn142", className2: "cn143" },
    { className: "cn144", className2: "cn145" },
    { className: "cn146", className2: "cn147" }
];

export default function Page() {
  return (
    <>
      <StorefrontHeader className="cn1" data-cid="n1">
        <div className="cn2" data-cid="n2">
          <div className="cn3" data-cid="n3">
            <div className="cn4" data-cid="n4">
              <div className="cn5" data-cid="n5">
                <button className="cn6" data-cid="n6" data-component="button" aria-label="Menü öffnen">
                  <div className="cn7" data-cid="n7">
                    <span className="cn8" data-cid="n8" />
                    <span className="cn9" data-cid="n9" />
                    <span className="cn10" data-cid="n10" />
                  </div>
                </button>
              </div>
              <div className="cn11" data-cid="n11">
                <a className="cn12" data-cid="n12" data-component="link" href="/de/de">
                  <img className="cn13" data-cid="n13" data-component="image" alt="Spree" height="32" src="/assets/cloned/images/ccdab56ac016.png" width="90" />
                </a>
              </div>
              <div className="cn14" data-cid="n14">
                <div className="cn15" data-cid="n15">
                  <a className="cn16" data-cid="n16" data-component="link" href="https://demo.spreecommerce.org/de/de/wholesale">
                    Großhandel
                  </a>
                  <button className="cn17" data-cid="n17" data-component="button" aria-controls="radix-_R_579iujpfivb_" aria-expanded="false" aria-haspopup="dialog" aria-label="Region und Sprache" type="button">
                    <span className="cn18" data-cid="n18" aria-hidden="true">
                      <img className="cn19" data-cid="n19" data-component="image" alt="" height="18" src="/assets/cloned/svg/e9231f4329fd.svg" width="18" />
                    </span>
                  </button>
                </div>
                <button className="cn20" data-cid="n20" data-component="button" aria-controls="search-overlay" aria-expanded="false" aria-label="Suche öffnen">
                  <svg className="cn21" data-cid="n21" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="m21 21-4.34-4.34" />
                    <circle cx="11" cy="11" r="8" />
                  </svg>
                </button>
                <div className="cn22" data-cid="n22">
                  <a className="cn23" data-cid="n23" data-component="link" aria-label="Konto" href="https://demo.spreecommerce.org/de/de/account">
                    <svg className="cn24" data-cid="n24" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                      <circle cx="12" cy="7" r="4" />
                    </svg>
                  </a>
                </div>
                <button className="cn25" data-cid="n25" data-component="button" aria-label="Warenkorb öffnen">
                  <svg className="cn26" data-cid="n26" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 10a4 4 0 0 1-8 0" />
                    <path d="M3.103 6.034h17.794" />
                    <path d="M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="cn27" data-cid="n27" id="search-overlay">
          <div className="cn28" data-cid="n28">
            <div className="cn29" data-cid="n29">
              <div className="cn30" data-cid="n30">
                <form className="cn31" data-cid="n31">
                  <div className="cn32" data-cid="n32" role="group">
                    <input className="cn33" data-cid="n33" data-component="select" aria-autocomplete="list" aria-controls="search-suggestions" aria-expanded="false" aria-label="Suche..." placeholder="Suche..." role="combobox" type="search" value="" />
                    <div className="cn34" data-cid="n34" role="group">
                      <svg className="cn35" data-cid="n35" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="m21 21-4.34-4.34" />
                        <circle cx="11" cy="11" r="8" />
                      </svg>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <button className="cn36" data-cid="n36" data-component="button" aria-label="Suche schließen">
              <svg className="cn37" data-cid="n37" data-component="icon" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M18 6 6 18" />
                <path d="m6 6 12 12" />
              </svg>
            </button>
          </div>
        </div>
      </StorefrontHeader>
      <nav className="cn38" data-cid="n38" aria-label="Category navigation">
        <ul className="cn39" data-cid="n39">
          <li className="cn40" data-cid="n40">
            <a className="cn41" data-cid="n41" data-component="link" href="/de/de/c/kitchen">
              Küche
            </a>
            <ul className="cn42" data-cid="n42">
              {NavigationLink_data.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids[i]} styles={NavigationLink_styles[i]} />)}
            </ul>
          </li>
          {MegaMenuCategory_data.map((d, i) => <MegaMenuCategory key={i} d={d} cids={MegaMenuCategory_cids[i]} styles={MegaMenuCategory_styles[i]} />)}
          <li className="cn82" data-cid="n82">
            <a className="cn83" data-cid="n83" data-component="link" href="https://demo.spreecommerce.org/de/de/c/personal-care">
              Körperpflege
            </a>
            <ul className="cn84" data-cid="n84">
              {NavigationLink_data2.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids2[i]} styles={NavigationLink_styles2[i]} />)}
            </ul>
          </li>
        </ul>
      </nav>
      <main className="cn93" data-cid="n93">
        <div className="cn94" data-cid="n94">
          <div className="cn95" data-cid="n95">
            <svg className="cn96" data-cid="n96" data-component="image" aria-hidden="true" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round">
              <path d="M16 10a4 4 0 0 1-8 0" />
              <path d="M3.103 6.034h17.794" />
              <path d="M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z" />
            </svg>
            <h1 className="cn97" data-cid="n97" data-component="heading">
              Ihr Warenkorb ist leer
            </h1>
            <p className="cn98" data-cid="n98">
              Es sieht so aus, als hätten Sie noch nichts in Ihren Warenkorb gelegt.
            </p>
            <div className="cn99" data-cid="n99">
              <a className="cn100" data-cid="n100" data-component="button" href="/de/de/products">
                Weiter einkaufen
              </a>
            </div>
          </div>
        </div>
      </main>
      <StorefrontFooter className="cn101" data-cid="n101">
        <div className="cn102" data-cid="n102">
          <div className="cn103" data-cid="n103">
            <div className="cn104" data-cid="n104">
              <span className="cn105" data-cid="n105">
                Spree
              </span>
              <p className="cn106" data-cid="n106">
                Open-Source-E-Commerce basierend auf Spree REST API, TypeScript SDK und Next.js. Selbst hosten. Eigene Daten. Keine Plattformgebühren.
              </p>
              <div className="cn107" data-cid="n107">
                <a className="cn108" data-cid="n108" data-component="link" href="https://github.com/spree/storefront" rel="noopener noreferrer" target="_blank">
                  Diese Storefront auf GitHub forken→
                </a>
                <a className="cn109" data-cid="n109" data-component="link" href="https://spreecommerce.org/docs/developer/getting-started/quickstart" rel="noopener noreferrer" target="_blank">
                  Schnellstartanleitung
                </a>
                <a className="cn110" data-cid="n110" data-component="link" href="https://spreecommerce.org/" rel="noopener noreferrer" target="_blank">
                  Mehr über Spree Commerce erfahren
                </a>
              </div>
            </div>
            <div className="cn111" data-cid="n111">
              <h3 className="cn112" data-cid="n112" data-component="heading">
                Shop
              </h3>
              <ul className="cn113" data-cid="n113">
                {NavigationLink_data3.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids3[i]} styles={NavigationLink_styles3[i]} />)}
              </ul>
            </div>
            <div className="cn126" data-cid="n126">
              <h3 className="cn127" data-cid="n127" data-component="heading">
                Konto
              </h3>
              <ul className="cn128" data-cid="n128">
                {NavigationLink_data4.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids4[i]} styles={NavigationLink_styles4[i]} />)}
              </ul>
            </div>
            <div className="cn137" data-cid="n137">
              <h3 className="cn138" data-cid="n138" data-component="heading">
                Richtlinien
              </h3>
              <ul className="cn139" data-cid="n139">
                {NavigationLink_data5.map((d, i) => <NavigationLink key={i} d={d} cids={NavigationLink_cids5[i]} styles={NavigationLink_styles5[i]} />)}
              </ul>
            </div>
          </div>
          <div className="cn148" data-cid="n148">
            <p className="cn149" data-cid="n149">
              {"© 2026 Spree. Betrieben von "}
              <a className="cn150" data-cid="n150" data-component="link" href="https://spreecommerce.org/" target="_blank">
                Spree Commerce
              </a>
              {" & Next.js."}
            </p>
          </div>
        </div>
      </StorefrontFooter>
      <section className="cn151" data-cid="n151" aria-atomic="false" aria-label="Notifications alt+T" aria-live="polite" aria-relevant="additions text" />
    </>
  );
}
